
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr  9 2024 12:04:50 IST (Apr  9 2024 06:34:50 UTC)

// Verification Directory fv/top 

module RC_CG_MOD_8(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_9(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module decoder(clk, rst, data_10b_in, par_en, data_8b_out);
  input clk, rst, par_en;
  input [9:0] data_10b_in;
  output [7:0] data_8b_out;
  wire clk, rst, par_en;
  wire [9:0] data_10b_in;
  wire [7:0] data_8b_out;
  wire [4:0] temp_5b;
  wire [2:0] temp_3b;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_71, rc_gclk;
  wire rc_gclk_541;
  RC_CG_MOD_8 RC_CG_HIER_INST8(.enable (n_71), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_9 RC_CG_HIER_INST9(.enable (n_69), .ck_in (clk), .ck_out
       (rc_gclk_541), .test (1'b0));
  INVXL g889(.A (n_71), .Y (n_69));
  DFFQXL \data_8b_out_reg[0] (.CK (rc_gclk), .D (temp_5b[0]), .Q
       (data_8b_out[0]));
  DFFQXL \data_8b_out_reg[1] (.CK (rc_gclk), .D (temp_5b[1]), .Q
       (data_8b_out[1]));
  DFFQXL \data_8b_out_reg[2] (.CK (rc_gclk), .D (temp_5b[2]), .Q
       (data_8b_out[2]));
  DFFQXL \data_8b_out_reg[3] (.CK (rc_gclk), .D (temp_5b[3]), .Q
       (data_8b_out[3]));
  DFFQXL \data_8b_out_reg[4] (.CK (rc_gclk), .D (temp_5b[4]), .Q
       (data_8b_out[4]));
  DFFQXL \data_8b_out_reg[5] (.CK (rc_gclk), .D (temp_3b[0]), .Q
       (data_8b_out[5]));
  DFFQXL \data_8b_out_reg[6] (.CK (rc_gclk), .D (temp_3b[1]), .Q
       (data_8b_out[6]));
  DFFQXL \data_8b_out_reg[7] (.CK (rc_gclk), .D (temp_3b[2]), .Q
       (data_8b_out[7]));
  DFFQXL \temp_3b_reg[0] (.CK (rc_gclk_541), .D (n_49), .Q
       (temp_3b[0]));
  DFFQXL \temp_3b_reg[1] (.CK (rc_gclk_541), .D (n_47), .Q
       (temp_3b[1]));
  DFFQXL \temp_3b_reg[2] (.CK (rc_gclk_541), .D (n_39), .Q
       (temp_3b[2]));
  DFFQXL \temp_5b_reg[0] (.CK (rc_gclk_541), .D (n_65), .Q
       (temp_5b[0]));
  DFFQXL \temp_5b_reg[1] (.CK (rc_gclk_541), .D (n_64), .Q
       (temp_5b[1]));
  DFFQXL \temp_5b_reg[2] (.CK (rc_gclk_541), .D (n_67), .Q
       (temp_5b[2]));
  DFFQXL \temp_5b_reg[3] (.CK (rc_gclk_541), .D (n_68), .Q
       (temp_5b[3]));
  DFFQXL \temp_5b_reg[4] (.CK (rc_gclk_541), .D (n_66), .Q
       (temp_5b[4]));
  NOR2XL g2133__2398(.A (rst), .B (n_63), .Y (n_68));
  NOR2XL g2134__5107(.A (rst), .B (n_62), .Y (n_67));
  AOI21X1 g2135__6260(.A0 (n_54), .A1 (n_58), .B0 (rst), .Y (n_66));
  NOR2XL g2136__4319(.A (rst), .B (n_60), .Y (n_65));
  NOR2XL g2137__8428(.A (rst), .B (n_61), .Y (n_64));
  AOI221X1 g2138__5526(.A0 (n_25), .A1 (n_40), .B0 (data_10b_in[2]),
       .B1 (n_57), .C0 (n_53), .Y (n_63));
  AOI32X1 g2139__6783(.A0 (n_5), .A1 (n_14), .A2 (n_34), .B0
       (data_10b_in[3]), .B1 (n_59), .Y (n_62));
  AOI211XL g2140__3680(.A0 (n_7), .A1 (n_0), .B0 (n_37), .C0 (n_53), .Y
       (n_61));
  AOI21XL g2141__1617(.A0 (data_10b_in[5]), .A1 (n_52), .B0 (n_56), .Y
       (n_60));
  NAND2XL g2142__2802(.A (n_36), .B (n_55), .Y (n_59));
  OAI2BB1X1 g2143__1705(.A0N (n_48), .A1N (n_50), .B0 (data_10b_in[1]),
       .Y (n_58));
  OAI21X1 g2144__5122(.A0 (data_10b_in[4]), .A1 (n_51), .B0 (n_33), .Y
       (n_57));
  OAI2BB1X1 g2145__8246(.A0N (n_25), .A1N (n_22), .B0 (n_54), .Y
       (n_56));
  OAI22XL g2148__7098(.A0 (data_10b_in[5]), .A1 (n_46), .B0 (n_2), .B1
       (n_43), .Y (n_55));
  MX2XL g2149__6131(.A (n_46), .B (n_43), .S0 (data_10b_in[3]), .Y
       (n_52));
  OAI211X1 g2150__1881(.A0 (n_32), .A1 (n_43), .B0 (data_10b_in[1]),
       .C0 (data_10b_in[5]), .Y (n_54));
  OAI32X1 g2151__5115(.A0 (n_3), .A1 (n_12), .A2 (n_31), .B0 (n_15),
       .B1 (n_42), .Y (n_53));
  AOI21XL g2156__7482(.A0 (data_10b_in[5]), .A1 (n_13), .B0 (n_45), .Y
       (n_51));
  AOI222X1 g2157__4733(.A0 (n_7), .A1 (n_23), .B0 (n_14), .B1 (n_16),
       .C0 (n_9), .C1 (n_38), .Y (n_50));
  AOI211XL g2158__6161(.A0 (n_26), .A1 (n_29), .B0 (data_10b_in[8]),
       .C0 (rst), .Y (n_49));
  NAND2XL g2159__9315(.A (data_10b_in[2]), .B (n_41), .Y (n_48));
  AOI211XL g2161__9945(.A0 (n_28), .A1 (n_27), .B0 (data_10b_in[9]),
       .C0 (rst), .Y (n_47));
  INVXL g2162(.A (n_44), .Y (n_45));
  AOI21XL g2163__2883(.A0 (n_5), .A1 (n_9), .B0 (n_41), .Y (n_42));
  OAI22X1 g2164__2346(.A0 (n_11), .A1 (n_35), .B0 (data_10b_in[0]), .B1
       (n_15), .Y (n_46));
  AOI32X1 g2165__1666(.A0 (data_10b_in[3]), .A1 (data_10b_in[5]), .A2
       (n_6), .B0 (n_10), .B1 (n_23), .Y (n_44));
  MX2XL g2166__7410(.A (n_24), .B (n_17), .S0 (data_10b_in[0]), .Y
       (n_43));
  NOR2BX1 g2167__6417(.AN (n_7), .B (n_12), .Y (n_40));
  AOI2BB1XL g2168__5477(.A0N (n_21), .A1N (n_20), .B0 (rst), .Y (n_39));
  AND2XL g2169__2398(.A (n_6), .B (n_23), .Y (n_41));
  OAI21XL g2170__5107(.A0 (data_10b_in[2]), .A1 (n_5), .B0 (n_1), .Y
       (n_38));
  NOR4X1 g2171__6260(.A (n_4), .B (data_10b_in[5]), .C
       (data_10b_in[3]), .D (n_3), .Y (n_37));
  OAI211X1 g2172__4319(.A0 (n_17), .A1 (n_16), .B0 (data_10b_in[1]),
       .C0 (n_30), .Y (n_36));
  INVXL g2173(.A (n_24), .Y (n_35));
  OAI22X1 g2175__8428(.A0 (n_2), .A1 (n_11), .B0 (n_3), .B1 (n_8), .Y
       (n_34));
  OAI211X1 g2176__5526(.A0 (data_10b_in[4]), .A1 (data_10b_in[3]), .B0
       (data_10b_in[1]), .C0 (n_16), .Y (n_33));
  INVXL g2177(.A (n_31), .Y (n_32));
  NAND2XL g2178__6783(.A (n_17), .B (n_16), .Y (n_30));
  NAND2XL g2179__3680(.A (data_10b_in[9]), .B (n_18), .Y (n_29));
  OAI2BB1X1 g2180__1617(.A0N (data_10b_in[7]), .A1N (data_10b_in[8]),
       .B0 (data_10b_in[6]), .Y (n_28));
  NAND2XL g2181__2802(.A (data_10b_in[8]), .B (n_18), .Y (n_27));
  OAI2BB1X1 g2182__1705(.A0N (data_10b_in[7]), .A1N (data_10b_in[9]),
       .B0 (data_10b_in[6]), .Y (n_26));
  NAND2XL g2183__5122(.A (data_10b_in[3]), .B (n_17), .Y (n_31));
  NOR2XL g2184__8246(.A (n_15), .B (n_8), .Y (n_22));
  NOR4BX1 g2185__7098(.AN (data_10b_in[6]), .B (data_10b_in[9]), .C
       (data_10b_in[8]), .D (data_10b_in[7]), .Y (n_21));
  AOI21XL g2186__6131(.A0 (data_10b_in[9]), .A1 (data_10b_in[8]), .B0
       (n_19), .Y (n_20));
  OAI22X1 g2187__1881(.A0 (data_10b_in[1]), .A1 (n_5), .B0
       (data_10b_in[3]), .B1 (n_3), .Y (n_25));
  OAI2BB1X1 g2188__5115(.A0N (data_10b_in[2]), .A1N (n_4), .B0 (n_1),
       .Y (n_24));
  OAI22X1 g2189__7482(.A0 (data_10b_in[3]), .A1 (n_2), .B0
       (data_10b_in[5]), .B1 (n_5), .Y (n_23));
  INVXL g2190(.A (n_18), .Y (n_19));
  INVX1 g2191(.A (n_15), .Y (n_14));
  NOR2X1 g2192__4733(.A (rst), .B (par_en), .Y (n_71));
  NOR2BX1 g2193__6161(.AN (data_10b_in[7]), .B (data_10b_in[6]), .Y
       (n_18));
  NOR2X1 g2194__9315(.A (data_10b_in[2]), .B (data_10b_in[4]), .Y
       (n_17));
  NOR2X1 g2195__9945(.A (data_10b_in[0]), .B (data_10b_in[5]), .Y
       (n_16));
  NAND2X1 g2196__2883(.A (data_10b_in[2]), .B (data_10b_in[4]), .Y
       (n_15));
  INVXL g2198(.A (n_11), .Y (n_10));
  INVXL g2199(.A (n_9), .Y (n_8));
  INVXL g2200(.A (n_7), .Y (n_1));
  NOR2X1 g2201__2346(.A (data_10b_in[0]), .B (n_3), .Y (n_13));
  NAND2XL g2202__1666(.A (data_10b_in[0]), .B (data_10b_in[5]), .Y
       (n_12));
  NAND2X1 g2203__7410(.A (data_10b_in[0]), .B (n_3), .Y (n_11));
  NOR2X1 g2204__6417(.A (data_10b_in[5]), .B (n_6), .Y (n_9));
  NOR2X1 g2205__5477(.A (data_10b_in[2]), .B (n_4), .Y (n_7));
  INVX1 g2206(.A (data_10b_in[0]), .Y (n_6));
  INVX1 g2207(.A (data_10b_in[3]), .Y (n_5));
  INVX1 g2208(.A (data_10b_in[4]), .Y (n_4));
  INVX1 g2209(.A (data_10b_in[1]), .Y (n_3));
  INVX1 g2210(.A (data_10b_in[5]), .Y (n_2));
  NAND2BXL g2__2398(.AN (n_13), .B (n_44), .Y (n_0));
endmodule

module RC_CG_MOD_10(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_11(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module decoder_92(clk, rst, data_10b_in, par_en, data_8b_out);
  input clk, rst, par_en;
  input [9:0] data_10b_in;
  output [7:0] data_8b_out;
  wire clk, rst, par_en;
  wire [9:0] data_10b_in;
  wire [7:0] data_8b_out;
  wire [4:0] temp_5b;
  wire [2:0] temp_3b;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_71, rc_gclk;
  wire rc_gclk_541;
  RC_CG_MOD_10 RC_CG_HIER_INST10(.enable (n_71), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_11 RC_CG_HIER_INST11(.enable (n_69), .ck_in (clk), .ck_out
       (rc_gclk_541), .test (1'b0));
  INVXL g889(.A (n_71), .Y (n_69));
  DFFQXL \data_8b_out_reg[0] (.CK (rc_gclk), .D (temp_5b[0]), .Q
       (data_8b_out[0]));
  DFFQXL \data_8b_out_reg[1] (.CK (rc_gclk), .D (temp_5b[1]), .Q
       (data_8b_out[1]));
  DFFQXL \data_8b_out_reg[2] (.CK (rc_gclk), .D (temp_5b[2]), .Q
       (data_8b_out[2]));
  DFFQXL \data_8b_out_reg[3] (.CK (rc_gclk), .D (temp_5b[3]), .Q
       (data_8b_out[3]));
  DFFQXL \data_8b_out_reg[4] (.CK (rc_gclk), .D (temp_5b[4]), .Q
       (data_8b_out[4]));
  DFFQXL \data_8b_out_reg[5] (.CK (rc_gclk), .D (temp_3b[0]), .Q
       (data_8b_out[5]));
  DFFQXL \data_8b_out_reg[6] (.CK (rc_gclk), .D (temp_3b[1]), .Q
       (data_8b_out[6]));
  DFFQXL \data_8b_out_reg[7] (.CK (rc_gclk), .D (temp_3b[2]), .Q
       (data_8b_out[7]));
  DFFQXL \temp_3b_reg[0] (.CK (rc_gclk_541), .D (n_49), .Q
       (temp_3b[0]));
  DFFQXL \temp_3b_reg[1] (.CK (rc_gclk_541), .D (n_47), .Q
       (temp_3b[1]));
  DFFQXL \temp_3b_reg[2] (.CK (rc_gclk_541), .D (n_39), .Q
       (temp_3b[2]));
  DFFQXL \temp_5b_reg[0] (.CK (rc_gclk_541), .D (n_65), .Q
       (temp_5b[0]));
  DFFQXL \temp_5b_reg[1] (.CK (rc_gclk_541), .D (n_64), .Q
       (temp_5b[1]));
  DFFQXL \temp_5b_reg[2] (.CK (rc_gclk_541), .D (n_67), .Q
       (temp_5b[2]));
  DFFQXL \temp_5b_reg[3] (.CK (rc_gclk_541), .D (n_68), .Q
       (temp_5b[3]));
  DFFQXL \temp_5b_reg[4] (.CK (rc_gclk_541), .D (n_66), .Q
       (temp_5b[4]));
  NOR2XL g2133__5107(.A (rst), .B (n_63), .Y (n_68));
  NOR2XL g2134__6260(.A (rst), .B (n_62), .Y (n_67));
  AOI21X1 g2135__4319(.A0 (n_54), .A1 (n_58), .B0 (rst), .Y (n_66));
  NOR2XL g2136__8428(.A (rst), .B (n_60), .Y (n_65));
  NOR2XL g2137__5526(.A (rst), .B (n_61), .Y (n_64));
  AOI221X1 g2138__6783(.A0 (n_25), .A1 (n_40), .B0 (data_10b_in[2]),
       .B1 (n_57), .C0 (n_53), .Y (n_63));
  AOI32X1 g2139__3680(.A0 (n_5), .A1 (n_14), .A2 (n_34), .B0
       (data_10b_in[3]), .B1 (n_59), .Y (n_62));
  AOI211XL g2140__1617(.A0 (n_7), .A1 (n_0), .B0 (n_37), .C0 (n_53), .Y
       (n_61));
  AOI21XL g2141__2802(.A0 (data_10b_in[5]), .A1 (n_52), .B0 (n_56), .Y
       (n_60));
  NAND2XL g2142__1705(.A (n_36), .B (n_55), .Y (n_59));
  OAI2BB1X1 g2143__5122(.A0N (n_48), .A1N (n_50), .B0 (data_10b_in[1]),
       .Y (n_58));
  OAI21X1 g2144__8246(.A0 (data_10b_in[4]), .A1 (n_51), .B0 (n_33), .Y
       (n_57));
  OAI2BB1X1 g2145__7098(.A0N (n_25), .A1N (n_22), .B0 (n_54), .Y
       (n_56));
  OAI22XL g2148__6131(.A0 (data_10b_in[5]), .A1 (n_46), .B0 (n_2), .B1
       (n_43), .Y (n_55));
  MX2XL g2149__1881(.A (n_46), .B (n_43), .S0 (data_10b_in[3]), .Y
       (n_52));
  OAI211X1 g2150__5115(.A0 (n_32), .A1 (n_43), .B0 (data_10b_in[1]),
       .C0 (data_10b_in[5]), .Y (n_54));
  OAI32X1 g2151__7482(.A0 (n_3), .A1 (n_12), .A2 (n_31), .B0 (n_15),
       .B1 (n_42), .Y (n_53));
  AOI21XL g2156__4733(.A0 (data_10b_in[5]), .A1 (n_13), .B0 (n_45), .Y
       (n_51));
  AOI222X1 g2157__6161(.A0 (n_7), .A1 (n_23), .B0 (n_14), .B1 (n_16),
       .C0 (n_9), .C1 (n_38), .Y (n_50));
  AOI211XL g2158__9315(.A0 (n_26), .A1 (n_29), .B0 (data_10b_in[8]),
       .C0 (rst), .Y (n_49));
  NAND2XL g2159__9945(.A (data_10b_in[2]), .B (n_41), .Y (n_48));
  AOI211XL g2161__2883(.A0 (n_28), .A1 (n_27), .B0 (data_10b_in[9]),
       .C0 (rst), .Y (n_47));
  INVXL g2162(.A (n_44), .Y (n_45));
  AOI21XL g2163__2346(.A0 (n_5), .A1 (n_9), .B0 (n_41), .Y (n_42));
  OAI22X1 g2164__1666(.A0 (n_11), .A1 (n_35), .B0 (data_10b_in[0]), .B1
       (n_15), .Y (n_46));
  AOI32X1 g2165__7410(.A0 (data_10b_in[3]), .A1 (data_10b_in[5]), .A2
       (n_6), .B0 (n_10), .B1 (n_23), .Y (n_44));
  MX2XL g2166__6417(.A (n_24), .B (n_17), .S0 (data_10b_in[0]), .Y
       (n_43));
  NOR2BX1 g2167__5477(.AN (n_7), .B (n_12), .Y (n_40));
  AOI2BB1XL g2168__2398(.A0N (n_21), .A1N (n_20), .B0 (rst), .Y (n_39));
  AND2XL g2169__5107(.A (n_6), .B (n_23), .Y (n_41));
  OAI21XL g2170__6260(.A0 (data_10b_in[2]), .A1 (n_5), .B0 (n_1), .Y
       (n_38));
  NOR4X1 g2171__4319(.A (n_4), .B (data_10b_in[5]), .C
       (data_10b_in[3]), .D (n_3), .Y (n_37));
  OAI211X1 g2172__8428(.A0 (n_17), .A1 (n_16), .B0 (data_10b_in[1]),
       .C0 (n_30), .Y (n_36));
  INVXL g2173(.A (n_24), .Y (n_35));
  OAI22X1 g2175__5526(.A0 (n_2), .A1 (n_11), .B0 (n_3), .B1 (n_8), .Y
       (n_34));
  OAI211X1 g2176__6783(.A0 (data_10b_in[4]), .A1 (data_10b_in[3]), .B0
       (data_10b_in[1]), .C0 (n_16), .Y (n_33));
  INVXL g2177(.A (n_31), .Y (n_32));
  NAND2XL g2178__3680(.A (n_17), .B (n_16), .Y (n_30));
  NAND2XL g2179__1617(.A (data_10b_in[9]), .B (n_18), .Y (n_29));
  OAI2BB1X1 g2180__2802(.A0N (data_10b_in[7]), .A1N (data_10b_in[8]),
       .B0 (data_10b_in[6]), .Y (n_28));
  NAND2XL g2181__1705(.A (data_10b_in[8]), .B (n_18), .Y (n_27));
  OAI2BB1X1 g2182__5122(.A0N (data_10b_in[7]), .A1N (data_10b_in[9]),
       .B0 (data_10b_in[6]), .Y (n_26));
  NAND2XL g2183__8246(.A (data_10b_in[3]), .B (n_17), .Y (n_31));
  NOR2XL g2184__7098(.A (n_15), .B (n_8), .Y (n_22));
  NOR4BX1 g2185__6131(.AN (data_10b_in[6]), .B (data_10b_in[9]), .C
       (data_10b_in[8]), .D (data_10b_in[7]), .Y (n_21));
  AOI21XL g2186__1881(.A0 (data_10b_in[9]), .A1 (data_10b_in[8]), .B0
       (n_19), .Y (n_20));
  OAI22X1 g2187__5115(.A0 (data_10b_in[1]), .A1 (n_5), .B0
       (data_10b_in[3]), .B1 (n_3), .Y (n_25));
  OAI2BB1X1 g2188__7482(.A0N (data_10b_in[2]), .A1N (n_4), .B0 (n_1),
       .Y (n_24));
  OAI22X1 g2189__4733(.A0 (data_10b_in[3]), .A1 (n_2), .B0
       (data_10b_in[5]), .B1 (n_5), .Y (n_23));
  INVXL g2190(.A (n_18), .Y (n_19));
  INVX1 g2191(.A (n_15), .Y (n_14));
  NOR2X1 g2192__6161(.A (rst), .B (par_en), .Y (n_71));
  NOR2BX1 g2193__9315(.AN (data_10b_in[7]), .B (data_10b_in[6]), .Y
       (n_18));
  NOR2X1 g2194__9945(.A (data_10b_in[2]), .B (data_10b_in[4]), .Y
       (n_17));
  NOR2X1 g2195__2883(.A (data_10b_in[0]), .B (data_10b_in[5]), .Y
       (n_16));
  NAND2X1 g2196__2346(.A (data_10b_in[2]), .B (data_10b_in[4]), .Y
       (n_15));
  INVXL g2198(.A (n_11), .Y (n_10));
  INVXL g2199(.A (n_9), .Y (n_8));
  INVXL g2200(.A (n_7), .Y (n_1));
  NOR2X1 g2201__1666(.A (data_10b_in[0]), .B (n_3), .Y (n_13));
  NAND2XL g2202__7410(.A (data_10b_in[0]), .B (data_10b_in[5]), .Y
       (n_12));
  NAND2X1 g2203__6417(.A (data_10b_in[0]), .B (n_3), .Y (n_11));
  NOR2X1 g2204__5477(.A (data_10b_in[5]), .B (n_6), .Y (n_9));
  NOR2X1 g2205__2398(.A (data_10b_in[2]), .B (n_4), .Y (n_7));
  INVX1 g2206(.A (data_10b_in[0]), .Y (n_6));
  INVX1 g2207(.A (data_10b_in[3]), .Y (n_5));
  INVX1 g2208(.A (data_10b_in[4]), .Y (n_4));
  INVX1 g2209(.A (data_10b_in[1]), .Y (n_3));
  INVX1 g2210(.A (data_10b_in[5]), .Y (n_2));
  NAND2BXL g2__5107(.AN (n_13), .B (n_44), .Y (n_0));
endmodule

module RC_CG_MOD_12(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_13(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module decoder_91(clk, rst, data_10b_in, par_en, data_8b_out);
  input clk, rst, par_en;
  input [9:0] data_10b_in;
  output [7:0] data_8b_out;
  wire clk, rst, par_en;
  wire [9:0] data_10b_in;
  wire [7:0] data_8b_out;
  wire [4:0] temp_5b;
  wire [2:0] temp_3b;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_71, rc_gclk;
  wire rc_gclk_541;
  RC_CG_MOD_12 RC_CG_HIER_INST12(.enable (n_71), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_13 RC_CG_HIER_INST13(.enable (n_69), .ck_in (clk), .ck_out
       (rc_gclk_541), .test (1'b0));
  INVXL g889(.A (n_71), .Y (n_69));
  DFFQXL \data_8b_out_reg[0] (.CK (rc_gclk), .D (temp_5b[0]), .Q
       (data_8b_out[0]));
  DFFQXL \data_8b_out_reg[1] (.CK (rc_gclk), .D (temp_5b[1]), .Q
       (data_8b_out[1]));
  DFFQXL \data_8b_out_reg[2] (.CK (rc_gclk), .D (temp_5b[2]), .Q
       (data_8b_out[2]));
  DFFQXL \data_8b_out_reg[3] (.CK (rc_gclk), .D (temp_5b[3]), .Q
       (data_8b_out[3]));
  DFFQXL \data_8b_out_reg[4] (.CK (rc_gclk), .D (temp_5b[4]), .Q
       (data_8b_out[4]));
  DFFQXL \data_8b_out_reg[5] (.CK (rc_gclk), .D (temp_3b[0]), .Q
       (data_8b_out[5]));
  DFFQXL \data_8b_out_reg[6] (.CK (rc_gclk), .D (temp_3b[1]), .Q
       (data_8b_out[6]));
  DFFQXL \data_8b_out_reg[7] (.CK (rc_gclk), .D (temp_3b[2]), .Q
       (data_8b_out[7]));
  DFFQXL \temp_3b_reg[0] (.CK (rc_gclk_541), .D (n_49), .Q
       (temp_3b[0]));
  DFFQXL \temp_3b_reg[1] (.CK (rc_gclk_541), .D (n_47), .Q
       (temp_3b[1]));
  DFFQXL \temp_3b_reg[2] (.CK (rc_gclk_541), .D (n_39), .Q
       (temp_3b[2]));
  DFFQXL \temp_5b_reg[0] (.CK (rc_gclk_541), .D (n_65), .Q
       (temp_5b[0]));
  DFFQXL \temp_5b_reg[1] (.CK (rc_gclk_541), .D (n_64), .Q
       (temp_5b[1]));
  DFFQXL \temp_5b_reg[2] (.CK (rc_gclk_541), .D (n_67), .Q
       (temp_5b[2]));
  DFFQXL \temp_5b_reg[3] (.CK (rc_gclk_541), .D (n_68), .Q
       (temp_5b[3]));
  DFFQXL \temp_5b_reg[4] (.CK (rc_gclk_541), .D (n_66), .Q
       (temp_5b[4]));
  NOR2XL g2133__6260(.A (rst), .B (n_63), .Y (n_68));
  NOR2XL g2134__4319(.A (rst), .B (n_62), .Y (n_67));
  AOI21X1 g2135__8428(.A0 (n_54), .A1 (n_58), .B0 (rst), .Y (n_66));
  NOR2XL g2136__5526(.A (rst), .B (n_60), .Y (n_65));
  NOR2XL g2137__6783(.A (rst), .B (n_61), .Y (n_64));
  AOI221X1 g2138__3680(.A0 (n_25), .A1 (n_40), .B0 (data_10b_in[2]),
       .B1 (n_57), .C0 (n_53), .Y (n_63));
  AOI32X1 g2139__1617(.A0 (n_5), .A1 (n_14), .A2 (n_34), .B0
       (data_10b_in[3]), .B1 (n_59), .Y (n_62));
  AOI211XL g2140__2802(.A0 (n_7), .A1 (n_0), .B0 (n_37), .C0 (n_53), .Y
       (n_61));
  AOI21XL g2141__1705(.A0 (data_10b_in[5]), .A1 (n_52), .B0 (n_56), .Y
       (n_60));
  NAND2XL g2142__5122(.A (n_36), .B (n_55), .Y (n_59));
  OAI2BB1X1 g2143__8246(.A0N (n_48), .A1N (n_50), .B0 (data_10b_in[1]),
       .Y (n_58));
  OAI21X1 g2144__7098(.A0 (data_10b_in[4]), .A1 (n_51), .B0 (n_33), .Y
       (n_57));
  OAI2BB1X1 g2145__6131(.A0N (n_25), .A1N (n_22), .B0 (n_54), .Y
       (n_56));
  OAI22XL g2148__1881(.A0 (data_10b_in[5]), .A1 (n_46), .B0 (n_2), .B1
       (n_43), .Y (n_55));
  MX2XL g2149__5115(.A (n_46), .B (n_43), .S0 (data_10b_in[3]), .Y
       (n_52));
  OAI211X1 g2150__7482(.A0 (n_32), .A1 (n_43), .B0 (data_10b_in[1]),
       .C0 (data_10b_in[5]), .Y (n_54));
  OAI32X1 g2151__4733(.A0 (n_3), .A1 (n_12), .A2 (n_31), .B0 (n_15),
       .B1 (n_42), .Y (n_53));
  AOI21XL g2156__6161(.A0 (data_10b_in[5]), .A1 (n_13), .B0 (n_45), .Y
       (n_51));
  AOI222X1 g2157__9315(.A0 (n_7), .A1 (n_23), .B0 (n_14), .B1 (n_16),
       .C0 (n_9), .C1 (n_38), .Y (n_50));
  AOI211XL g2158__9945(.A0 (n_26), .A1 (n_29), .B0 (data_10b_in[8]),
       .C0 (rst), .Y (n_49));
  NAND2XL g2159__2883(.A (data_10b_in[2]), .B (n_41), .Y (n_48));
  AOI211XL g2161__2346(.A0 (n_28), .A1 (n_27), .B0 (data_10b_in[9]),
       .C0 (rst), .Y (n_47));
  INVXL g2162(.A (n_44), .Y (n_45));
  AOI21XL g2163__1666(.A0 (n_5), .A1 (n_9), .B0 (n_41), .Y (n_42));
  OAI22X1 g2164__7410(.A0 (n_11), .A1 (n_35), .B0 (data_10b_in[0]), .B1
       (n_15), .Y (n_46));
  AOI32X1 g2165__6417(.A0 (data_10b_in[3]), .A1 (data_10b_in[5]), .A2
       (n_6), .B0 (n_10), .B1 (n_23), .Y (n_44));
  MX2XL g2166__5477(.A (n_24), .B (n_17), .S0 (data_10b_in[0]), .Y
       (n_43));
  NOR2BX1 g2167__2398(.AN (n_7), .B (n_12), .Y (n_40));
  AOI2BB1XL g2168__5107(.A0N (n_21), .A1N (n_20), .B0 (rst), .Y (n_39));
  AND2XL g2169__6260(.A (n_6), .B (n_23), .Y (n_41));
  OAI21XL g2170__4319(.A0 (data_10b_in[2]), .A1 (n_5), .B0 (n_1), .Y
       (n_38));
  NOR4X1 g2171__8428(.A (n_4), .B (data_10b_in[5]), .C
       (data_10b_in[3]), .D (n_3), .Y (n_37));
  OAI211X1 g2172__5526(.A0 (n_17), .A1 (n_16), .B0 (data_10b_in[1]),
       .C0 (n_30), .Y (n_36));
  INVXL g2173(.A (n_24), .Y (n_35));
  OAI22X1 g2175__6783(.A0 (n_2), .A1 (n_11), .B0 (n_3), .B1 (n_8), .Y
       (n_34));
  OAI211X1 g2176__3680(.A0 (data_10b_in[4]), .A1 (data_10b_in[3]), .B0
       (data_10b_in[1]), .C0 (n_16), .Y (n_33));
  INVXL g2177(.A (n_31), .Y (n_32));
  NAND2XL g2178__1617(.A (n_17), .B (n_16), .Y (n_30));
  NAND2XL g2179__2802(.A (data_10b_in[9]), .B (n_18), .Y (n_29));
  OAI2BB1X1 g2180__1705(.A0N (data_10b_in[7]), .A1N (data_10b_in[8]),
       .B0 (data_10b_in[6]), .Y (n_28));
  NAND2XL g2181__5122(.A (data_10b_in[8]), .B (n_18), .Y (n_27));
  OAI2BB1X1 g2182__8246(.A0N (data_10b_in[7]), .A1N (data_10b_in[9]),
       .B0 (data_10b_in[6]), .Y (n_26));
  NAND2XL g2183__7098(.A (data_10b_in[3]), .B (n_17), .Y (n_31));
  NOR2XL g2184__6131(.A (n_15), .B (n_8), .Y (n_22));
  NOR4BX1 g2185__1881(.AN (data_10b_in[6]), .B (data_10b_in[9]), .C
       (data_10b_in[8]), .D (data_10b_in[7]), .Y (n_21));
  AOI21XL g2186__5115(.A0 (data_10b_in[9]), .A1 (data_10b_in[8]), .B0
       (n_19), .Y (n_20));
  OAI22X1 g2187__7482(.A0 (data_10b_in[1]), .A1 (n_5), .B0
       (data_10b_in[3]), .B1 (n_3), .Y (n_25));
  OAI2BB1X1 g2188__4733(.A0N (data_10b_in[2]), .A1N (n_4), .B0 (n_1),
       .Y (n_24));
  OAI22X1 g2189__6161(.A0 (data_10b_in[3]), .A1 (n_2), .B0
       (data_10b_in[5]), .B1 (n_5), .Y (n_23));
  INVXL g2190(.A (n_18), .Y (n_19));
  INVX1 g2191(.A (n_15), .Y (n_14));
  NOR2X1 g2192__9315(.A (rst), .B (par_en), .Y (n_71));
  NOR2BX1 g2193__9945(.AN (data_10b_in[7]), .B (data_10b_in[6]), .Y
       (n_18));
  NOR2X1 g2194__2883(.A (data_10b_in[2]), .B (data_10b_in[4]), .Y
       (n_17));
  NOR2X1 g2195__2346(.A (data_10b_in[0]), .B (data_10b_in[5]), .Y
       (n_16));
  NAND2X1 g2196__1666(.A (data_10b_in[2]), .B (data_10b_in[4]), .Y
       (n_15));
  INVXL g2198(.A (n_11), .Y (n_10));
  INVXL g2199(.A (n_9), .Y (n_8));
  INVXL g2200(.A (n_7), .Y (n_1));
  NOR2X1 g2201__7410(.A (data_10b_in[0]), .B (n_3), .Y (n_13));
  NAND2XL g2202__6417(.A (data_10b_in[0]), .B (data_10b_in[5]), .Y
       (n_12));
  NAND2X1 g2203__5477(.A (data_10b_in[0]), .B (n_3), .Y (n_11));
  NOR2X1 g2204__2398(.A (data_10b_in[5]), .B (n_6), .Y (n_9));
  NOR2X1 g2205__5107(.A (data_10b_in[2]), .B (n_4), .Y (n_7));
  INVX1 g2206(.A (data_10b_in[0]), .Y (n_6));
  INVX1 g2207(.A (data_10b_in[3]), .Y (n_5));
  INVX1 g2208(.A (data_10b_in[4]), .Y (n_4));
  INVX1 g2209(.A (data_10b_in[1]), .Y (n_3));
  INVX1 g2210(.A (data_10b_in[5]), .Y (n_2));
  NAND2BXL g2__6260(.AN (n_13), .B (n_44), .Y (n_0));
endmodule

module RC_CG_MOD_14(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_15(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module decoder_90(clk, rst, data_10b_in, par_en, data_8b_out);
  input clk, rst, par_en;
  input [9:0] data_10b_in;
  output [7:0] data_8b_out;
  wire clk, rst, par_en;
  wire [9:0] data_10b_in;
  wire [7:0] data_8b_out;
  wire [4:0] temp_5b;
  wire [2:0] temp_3b;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_71, rc_gclk;
  wire rc_gclk_541;
  RC_CG_MOD_14 RC_CG_HIER_INST14(.enable (n_71), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_15 RC_CG_HIER_INST15(.enable (n_69), .ck_in (clk), .ck_out
       (rc_gclk_541), .test (1'b0));
  INVXL g889(.A (n_71), .Y (n_69));
  DFFQXL \data_8b_out_reg[0] (.CK (rc_gclk), .D (temp_5b[0]), .Q
       (data_8b_out[0]));
  DFFQXL \data_8b_out_reg[1] (.CK (rc_gclk), .D (temp_5b[1]), .Q
       (data_8b_out[1]));
  DFFQXL \data_8b_out_reg[2] (.CK (rc_gclk), .D (temp_5b[2]), .Q
       (data_8b_out[2]));
  DFFQXL \data_8b_out_reg[3] (.CK (rc_gclk), .D (temp_5b[3]), .Q
       (data_8b_out[3]));
  DFFQXL \data_8b_out_reg[4] (.CK (rc_gclk), .D (temp_5b[4]), .Q
       (data_8b_out[4]));
  DFFQXL \data_8b_out_reg[5] (.CK (rc_gclk), .D (temp_3b[0]), .Q
       (data_8b_out[5]));
  DFFQXL \data_8b_out_reg[6] (.CK (rc_gclk), .D (temp_3b[1]), .Q
       (data_8b_out[6]));
  DFFQXL \data_8b_out_reg[7] (.CK (rc_gclk), .D (temp_3b[2]), .Q
       (data_8b_out[7]));
  DFFQXL \temp_3b_reg[0] (.CK (rc_gclk_541), .D (n_49), .Q
       (temp_3b[0]));
  DFFQXL \temp_3b_reg[1] (.CK (rc_gclk_541), .D (n_47), .Q
       (temp_3b[1]));
  DFFQXL \temp_3b_reg[2] (.CK (rc_gclk_541), .D (n_39), .Q
       (temp_3b[2]));
  DFFQXL \temp_5b_reg[0] (.CK (rc_gclk_541), .D (n_65), .Q
       (temp_5b[0]));
  DFFQXL \temp_5b_reg[1] (.CK (rc_gclk_541), .D (n_64), .Q
       (temp_5b[1]));
  DFFQXL \temp_5b_reg[2] (.CK (rc_gclk_541), .D (n_67), .Q
       (temp_5b[2]));
  DFFQXL \temp_5b_reg[3] (.CK (rc_gclk_541), .D (n_68), .Q
       (temp_5b[3]));
  DFFQXL \temp_5b_reg[4] (.CK (rc_gclk_541), .D (n_66), .Q
       (temp_5b[4]));
  NOR2XL g2133__4319(.A (rst), .B (n_63), .Y (n_68));
  NOR2XL g2134__8428(.A (rst), .B (n_62), .Y (n_67));
  AOI21X1 g2135__5526(.A0 (n_54), .A1 (n_58), .B0 (rst), .Y (n_66));
  NOR2XL g2136__6783(.A (rst), .B (n_60), .Y (n_65));
  NOR2XL g2137__3680(.A (rst), .B (n_61), .Y (n_64));
  AOI221X1 g2138__1617(.A0 (n_25), .A1 (n_40), .B0 (data_10b_in[2]),
       .B1 (n_57), .C0 (n_53), .Y (n_63));
  AOI32X1 g2139__2802(.A0 (n_5), .A1 (n_14), .A2 (n_34), .B0
       (data_10b_in[3]), .B1 (n_59), .Y (n_62));
  AOI211XL g2140__1705(.A0 (n_7), .A1 (n_0), .B0 (n_37), .C0 (n_53), .Y
       (n_61));
  AOI21XL g2141__5122(.A0 (data_10b_in[5]), .A1 (n_52), .B0 (n_56), .Y
       (n_60));
  NAND2XL g2142__8246(.A (n_36), .B (n_55), .Y (n_59));
  OAI2BB1X1 g2143__7098(.A0N (n_48), .A1N (n_50), .B0 (data_10b_in[1]),
       .Y (n_58));
  OAI21X1 g2144__6131(.A0 (data_10b_in[4]), .A1 (n_51), .B0 (n_33), .Y
       (n_57));
  OAI2BB1X1 g2145__1881(.A0N (n_25), .A1N (n_22), .B0 (n_54), .Y
       (n_56));
  OAI22XL g2148__5115(.A0 (data_10b_in[5]), .A1 (n_46), .B0 (n_2), .B1
       (n_43), .Y (n_55));
  MX2XL g2149__7482(.A (n_46), .B (n_43), .S0 (data_10b_in[3]), .Y
       (n_52));
  OAI211X1 g2150__4733(.A0 (n_32), .A1 (n_43), .B0 (data_10b_in[1]),
       .C0 (data_10b_in[5]), .Y (n_54));
  OAI32X1 g2151__6161(.A0 (n_3), .A1 (n_12), .A2 (n_31), .B0 (n_15),
       .B1 (n_42), .Y (n_53));
  AOI21XL g2156__9315(.A0 (data_10b_in[5]), .A1 (n_13), .B0 (n_45), .Y
       (n_51));
  AOI222X1 g2157__9945(.A0 (n_7), .A1 (n_23), .B0 (n_14), .B1 (n_16),
       .C0 (n_9), .C1 (n_38), .Y (n_50));
  AOI211XL g2158__2883(.A0 (n_26), .A1 (n_29), .B0 (data_10b_in[8]),
       .C0 (rst), .Y (n_49));
  NAND2XL g2159__2346(.A (data_10b_in[2]), .B (n_41), .Y (n_48));
  AOI211XL g2161__1666(.A0 (n_28), .A1 (n_27), .B0 (data_10b_in[9]),
       .C0 (rst), .Y (n_47));
  INVXL g2162(.A (n_44), .Y (n_45));
  AOI21XL g2163__7410(.A0 (n_5), .A1 (n_9), .B0 (n_41), .Y (n_42));
  OAI22X1 g2164__6417(.A0 (n_11), .A1 (n_35), .B0 (data_10b_in[0]), .B1
       (n_15), .Y (n_46));
  AOI32X1 g2165__5477(.A0 (data_10b_in[3]), .A1 (data_10b_in[5]), .A2
       (n_6), .B0 (n_10), .B1 (n_23), .Y (n_44));
  MX2XL g2166__2398(.A (n_24), .B (n_17), .S0 (data_10b_in[0]), .Y
       (n_43));
  NOR2BX1 g2167__5107(.AN (n_7), .B (n_12), .Y (n_40));
  AOI2BB1XL g2168__6260(.A0N (n_21), .A1N (n_20), .B0 (rst), .Y (n_39));
  AND2XL g2169__4319(.A (n_6), .B (n_23), .Y (n_41));
  OAI21XL g2170__8428(.A0 (data_10b_in[2]), .A1 (n_5), .B0 (n_1), .Y
       (n_38));
  NOR4X1 g2171__5526(.A (n_4), .B (data_10b_in[5]), .C
       (data_10b_in[3]), .D (n_3), .Y (n_37));
  OAI211X1 g2172__6783(.A0 (n_17), .A1 (n_16), .B0 (data_10b_in[1]),
       .C0 (n_30), .Y (n_36));
  INVXL g2173(.A (n_24), .Y (n_35));
  OAI22X1 g2175__3680(.A0 (n_2), .A1 (n_11), .B0 (n_3), .B1 (n_8), .Y
       (n_34));
  OAI211X1 g2176__1617(.A0 (data_10b_in[4]), .A1 (data_10b_in[3]), .B0
       (data_10b_in[1]), .C0 (n_16), .Y (n_33));
  INVXL g2177(.A (n_31), .Y (n_32));
  NAND2XL g2178__2802(.A (n_17), .B (n_16), .Y (n_30));
  NAND2XL g2179__1705(.A (data_10b_in[9]), .B (n_18), .Y (n_29));
  OAI2BB1X1 g2180__5122(.A0N (data_10b_in[7]), .A1N (data_10b_in[8]),
       .B0 (data_10b_in[6]), .Y (n_28));
  NAND2XL g2181__8246(.A (data_10b_in[8]), .B (n_18), .Y (n_27));
  OAI2BB1X1 g2182__7098(.A0N (data_10b_in[7]), .A1N (data_10b_in[9]),
       .B0 (data_10b_in[6]), .Y (n_26));
  NAND2XL g2183__6131(.A (data_10b_in[3]), .B (n_17), .Y (n_31));
  NOR2XL g2184__1881(.A (n_15), .B (n_8), .Y (n_22));
  NOR4BX1 g2185__5115(.AN (data_10b_in[6]), .B (data_10b_in[9]), .C
       (data_10b_in[8]), .D (data_10b_in[7]), .Y (n_21));
  AOI21XL g2186__7482(.A0 (data_10b_in[9]), .A1 (data_10b_in[8]), .B0
       (n_19), .Y (n_20));
  OAI22X1 g2187__4733(.A0 (data_10b_in[1]), .A1 (n_5), .B0
       (data_10b_in[3]), .B1 (n_3), .Y (n_25));
  OAI2BB1X1 g2188__6161(.A0N (data_10b_in[2]), .A1N (n_4), .B0 (n_1),
       .Y (n_24));
  OAI22X1 g2189__9315(.A0 (data_10b_in[3]), .A1 (n_2), .B0
       (data_10b_in[5]), .B1 (n_5), .Y (n_23));
  INVXL g2190(.A (n_18), .Y (n_19));
  INVX1 g2191(.A (n_15), .Y (n_14));
  NOR2X1 g2192__9945(.A (rst), .B (par_en), .Y (n_71));
  NOR2BX1 g2193__2883(.AN (data_10b_in[7]), .B (data_10b_in[6]), .Y
       (n_18));
  NOR2X1 g2194__2346(.A (data_10b_in[2]), .B (data_10b_in[4]), .Y
       (n_17));
  NOR2X1 g2195__1666(.A (data_10b_in[0]), .B (data_10b_in[5]), .Y
       (n_16));
  NAND2X1 g2196__7410(.A (data_10b_in[2]), .B (data_10b_in[4]), .Y
       (n_15));
  INVXL g2198(.A (n_11), .Y (n_10));
  INVXL g2199(.A (n_9), .Y (n_8));
  INVXL g2200(.A (n_7), .Y (n_1));
  NOR2X1 g2201__6417(.A (data_10b_in[0]), .B (n_3), .Y (n_13));
  NAND2XL g2202__5477(.A (data_10b_in[0]), .B (data_10b_in[5]), .Y
       (n_12));
  NAND2X1 g2203__2398(.A (data_10b_in[0]), .B (n_3), .Y (n_11));
  NOR2X1 g2204__5107(.A (data_10b_in[5]), .B (n_6), .Y (n_9));
  NOR2X1 g2205__6260(.A (data_10b_in[2]), .B (n_4), .Y (n_7));
  INVX1 g2206(.A (data_10b_in[0]), .Y (n_6));
  INVX1 g2207(.A (data_10b_in[3]), .Y (n_5));
  INVX1 g2208(.A (data_10b_in[4]), .Y (n_4));
  INVX1 g2209(.A (data_10b_in[1]), .Y (n_3));
  INVX1 g2210(.A (data_10b_in[5]), .Y (n_2));
  NAND2BXL g2__4319(.AN (n_13), .B (n_44), .Y (n_0));
endmodule

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_4(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_5(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_6(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_7(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_16(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_17(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module top(data_in, data_out, clk, rst);
  input [31:0] data_in;
  input clk, rst;
  output [31:0] data_out;
  wire [31:0] data_in;
  wire clk, rst;
  wire [31:0] data_out;
  wire [9:0] si_out;
  wire [9:0] si_out2;
  wire [9:0] si_out3;
  wire [9:0] si_out4;
  wire [5:0] E1_temp_6b;
  wire [9:0] en_out;
  wire [3:0] E1_temp_4b;
  wire [5:0] E2_temp_6b;
  wire [9:0] en_out2;
  wire [3:0] E2_temp_4b;
  wire [5:0] E3_temp_6b;
  wire [9:0] en_out3;
  wire [3:0] E3_temp_4b;
  wire [5:0] E4_temp_6b;
  wire [9:0] en_out4;
  wire [3:0] E4_temp_4b;
  wire [9:0] P1S01_shift_reg;
  wire [9:0] P1S02_shift_reg;
  wire [9:0] P1S03_shift_reg;
  wire [9:0] P1S04_shift_reg;
  wire [9:0] S1P01_shift_reg;
  wire [9:0] S1P02_shift_reg;
  wire [9:0] S1P03_shift_reg;
  wire [9:0] S1P04_shift_reg;
  wire [3:0] d_next;
  wire [2:0] s_next;
  wire [2:0] s_state;
  wire [3:0] d_state;
  wire [3:0] count_2;
  wire [3:0] count;
  wire E1_n_298, P1S01_n_37, de_en, en_en, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_235;
  wire n_236, n_237, n_238, n_239, n_240, n_241, n_242, n_243;
  wire n_244, n_245, n_246, n_247, n_248, n_249, n_250, n_251;
  wire n_252, n_253, n_254, n_255, n_256, n_257, n_258, n_259;
  wire n_260, n_261, n_262, n_263, n_264, n_265, n_266, n_267;
  wire n_268, n_269, n_270, n_271, n_272, n_273, n_274, n_275;
  wire n_276, n_277, n_278, n_279, n_280, n_281, n_282, n_283;
  wire n_284, n_285, n_286, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, n_294, n_295, n_296, n_297, n_298, n_299;
  wire n_300, n_301, n_302, n_303, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_311, n_312, n_313, n_314, n_315;
  wire n_316, n_317, n_318, n_319, n_320, n_321, n_322, n_323;
  wire n_324, n_325, n_326, n_327, n_328, n_329, n_330, n_331;
  wire n_332, n_333, n_334, n_335, n_336, n_337, n_338, n_339;
  wire n_340, n_341, n_342, n_343, n_344, n_345, n_346, n_347;
  wire n_348, n_349, n_350, n_351, n_352, n_353, n_354, n_355;
  wire n_356, n_357, n_358, n_361, n_362, n_363, n_364, n_365;
  wire n_366, n_367, n_368, n_369, n_370, n_371, n_372, n_373;
  wire n_374, n_375, n_408, n_409, n_410, n_411, n_445, n_449;
  wire p_en, rc_gclk, rc_gclk_448, rc_gclk_451, rc_gclk_695,
       rc_gclk_697, rc_gclk_699, rc_gclk_701;
  wire rc_gclk_703, rc_gclk_705, rc_gclk_708, s_en, ser_out, ser_out2,
       ser_out3, ser_out4;
  wire start;
  decoder D1(.clk (clk), .rst (rst), .data_10b_in (si_out), .par_en
       (de_en), .data_8b_out (data_out[7:0]));
  decoder_92 D2(.clk (clk), .rst (rst), .data_10b_in (si_out2), .par_en
       (de_en), .data_8b_out (data_out[15:8]));
  decoder_91 D3(.clk (clk), .rst (rst), .data_10b_in (si_out3), .par_en
       (de_en), .data_8b_out (data_out[23:16]));
  decoder_90 D4(.clk (clk), .rst (rst), .data_10b_in (si_out4), .par_en
       (de_en), .data_8b_out (data_out[31:24]));
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_369), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_368), .ck_in (clk), .ck_out
       (rc_gclk_695), .test (1'b0));
  RC_CG_MOD_2 RC_CG_HIER_INST2(.enable (n_370), .ck_in (clk), .ck_out
       (rc_gclk_697), .test (1'b0));
  RC_CG_MOD_3 RC_CG_HIER_INST3(.enable (n_408), .ck_in (clk), .ck_out
       (rc_gclk_699), .test (1'b0));
  RC_CG_MOD_4 RC_CG_HIER_INST4(.enable (n_371), .ck_in (clk), .ck_out
       (rc_gclk_701), .test (1'b0));
  RC_CG_MOD_5 RC_CG_HIER_INST5(.enable (P1S01_n_37), .ck_in (clk),
       .ck_out (rc_gclk_703), .test (1'b0));
  RC_CG_MOD_6 RC_CG_HIER_INST6(.enable (n_409), .ck_in (clk), .ck_out
       (rc_gclk_705), .test (1'b0));
  RC_CG_MOD_7 RC_CG_HIER_INST7(.enable (n_367), .ck_in (clk), .ck_out
       (rc_gclk_708), .test (1'b0));
  RC_CG_MOD_16 RC_CG_DECLONE_HIER_INST(.enable (E1_n_298), .ck_in
       (clk), .ck_out (rc_gclk_448), .test (1'b0));
  RC_CG_MOD_17 RC_CG_DECLONE_HIER_INST4476(.enable (n_449), .ck_in
       (clk), .ck_out (rc_gclk_451), .test (1'b0));
  DFFQXL \E1_data_10b_out_reg[0] (.CK (rc_gclk_448), .D
       (E1_temp_6b[0]), .Q (en_out[0]));
  DFFQXL \E1_data_10b_out_reg[1] (.CK (rc_gclk_448), .D
       (E1_temp_6b[1]), .Q (en_out[1]));
  DFFQXL \E1_data_10b_out_reg[2] (.CK (rc_gclk_448), .D
       (E1_temp_6b[2]), .Q (en_out[2]));
  DFFQXL \E1_data_10b_out_reg[3] (.CK (rc_gclk_448), .D
       (E1_temp_6b[3]), .Q (en_out[3]));
  DFFQXL \E1_data_10b_out_reg[4] (.CK (rc_gclk_448), .D
       (E1_temp_6b[4]), .Q (en_out[4]));
  DFFQXL \E1_data_10b_out_reg[5] (.CK (rc_gclk_448), .D
       (E1_temp_6b[5]), .Q (en_out[5]));
  DFFQXL \E1_data_10b_out_reg[6] (.CK (rc_gclk_448), .D
       (E1_temp_4b[0]), .Q (en_out[6]));
  DFFQXL \E1_data_10b_out_reg[7] (.CK (rc_gclk_448), .D
       (E1_temp_4b[1]), .Q (en_out[7]));
  DFFQXL \E1_data_10b_out_reg[8] (.CK (rc_gclk_448), .D
       (E1_temp_4b[2]), .Q (en_out[8]));
  DFFQXL \E1_data_10b_out_reg[9] (.CK (rc_gclk_448), .D
       (E1_temp_4b[3]), .Q (en_out[9]));
  DFFQXL \E1_temp_4b_reg[0] (.CK (rc_gclk_451), .D (n_215), .Q
       (E1_temp_4b[0]));
  DFFQXL \E1_temp_4b_reg[1] (.CK (rc_gclk_451), .D (n_208), .Q
       (E1_temp_4b[1]));
  DFFQXL \E1_temp_4b_reg[2] (.CK (rc_gclk_451), .D (n_180), .Q
       (E1_temp_4b[2]));
  DFFQXL \E1_temp_4b_reg[3] (.CK (rc_gclk_451), .D (n_144), .Q
       (E1_temp_4b[3]));
  DFFQXL \E1_temp_6b_reg[0] (.CK (rc_gclk_451), .D (n_269), .Q
       (E1_temp_6b[0]));
  DFFQXL \E1_temp_6b_reg[1] (.CK (rc_gclk_451), .D (n_239), .Q
       (E1_temp_6b[1]));
  DFFQXL \E1_temp_6b_reg[2] (.CK (rc_gclk_451), .D (n_251), .Q
       (E1_temp_6b[2]));
  DFFQXL \E1_temp_6b_reg[3] (.CK (rc_gclk_451), .D (n_276), .Q
       (E1_temp_6b[3]));
  DFFQXL \E1_temp_6b_reg[4] (.CK (rc_gclk_451), .D (n_262), .Q
       (E1_temp_6b[4]));
  DFFQXL \E1_temp_6b_reg[5] (.CK (rc_gclk_451), .D (n_274), .Q
       (E1_temp_6b[5]));
  DFFQXL \E2_data_10b_out_reg[0] (.CK (rc_gclk_448), .D
       (E2_temp_6b[0]), .Q (en_out2[0]));
  DFFQXL \E2_data_10b_out_reg[1] (.CK (rc_gclk_448), .D
       (E2_temp_6b[1]), .Q (en_out2[1]));
  DFFQXL \E2_data_10b_out_reg[2] (.CK (rc_gclk_448), .D
       (E2_temp_6b[2]), .Q (en_out2[2]));
  DFFQXL \E2_data_10b_out_reg[3] (.CK (rc_gclk_448), .D
       (E2_temp_6b[3]), .Q (en_out2[3]));
  DFFQXL \E2_data_10b_out_reg[4] (.CK (rc_gclk_448), .D
       (E2_temp_6b[4]), .Q (en_out2[4]));
  DFFQXL \E2_data_10b_out_reg[5] (.CK (rc_gclk_448), .D
       (E2_temp_6b[5]), .Q (en_out2[5]));
  DFFQXL \E2_data_10b_out_reg[6] (.CK (rc_gclk_448), .D
       (E2_temp_4b[0]), .Q (en_out2[6]));
  DFFQXL \E2_data_10b_out_reg[7] (.CK (rc_gclk_448), .D
       (E2_temp_4b[1]), .Q (en_out2[7]));
  DFFQXL \E2_data_10b_out_reg[8] (.CK (rc_gclk_448), .D
       (E2_temp_4b[2]), .Q (en_out2[8]));
  DFFQXL \E2_data_10b_out_reg[9] (.CK (rc_gclk_448), .D
       (E2_temp_4b[3]), .Q (en_out2[9]));
  DFFQXL \E2_temp_4b_reg[0] (.CK (rc_gclk_451), .D (n_207), .Q
       (E2_temp_4b[0]));
  DFFQXL \E2_temp_4b_reg[1] (.CK (rc_gclk_451), .D (n_218), .Q
       (E2_temp_4b[1]));
  DFFQXL \E2_temp_4b_reg[2] (.CK (rc_gclk_451), .D (n_181), .Q
       (E2_temp_4b[2]));
  DFFQXL \E2_temp_4b_reg[3] (.CK (rc_gclk_451), .D (n_145), .Q
       (E2_temp_4b[3]));
  DFFQXL \E2_temp_6b_reg[0] (.CK (rc_gclk_451), .D (n_270), .Q
       (E2_temp_6b[0]));
  DFFQXL \E2_temp_6b_reg[1] (.CK (rc_gclk_451), .D (n_241), .Q
       (E2_temp_6b[1]));
  DFFQXL \E2_temp_6b_reg[2] (.CK (rc_gclk_451), .D (n_253), .Q
       (E2_temp_6b[2]));
  DFFQXL \E2_temp_6b_reg[3] (.CK (rc_gclk_451), .D (n_272), .Q
       (E2_temp_6b[3]));
  DFFQXL \E2_temp_6b_reg[4] (.CK (rc_gclk_451), .D (n_264), .Q
       (E2_temp_6b[4]));
  DFFQXL \E2_temp_6b_reg[5] (.CK (rc_gclk_451), .D (n_277), .Q
       (E2_temp_6b[5]));
  DFFQXL \E3_data_10b_out_reg[0] (.CK (rc_gclk_448), .D
       (E3_temp_6b[0]), .Q (en_out3[0]));
  DFFQXL \E3_data_10b_out_reg[1] (.CK (rc_gclk_448), .D
       (E3_temp_6b[1]), .Q (en_out3[1]));
  DFFQXL \E3_data_10b_out_reg[2] (.CK (rc_gclk_448), .D
       (E3_temp_6b[2]), .Q (en_out3[2]));
  DFFQXL \E3_data_10b_out_reg[3] (.CK (rc_gclk_448), .D
       (E3_temp_6b[3]), .Q (en_out3[3]));
  DFFQXL \E3_data_10b_out_reg[4] (.CK (rc_gclk_448), .D
       (E3_temp_6b[4]), .Q (en_out3[4]));
  DFFQXL \E3_data_10b_out_reg[5] (.CK (rc_gclk_448), .D
       (E3_temp_6b[5]), .Q (en_out3[5]));
  DFFQXL \E3_data_10b_out_reg[6] (.CK (rc_gclk_448), .D
       (E3_temp_4b[0]), .Q (en_out3[6]));
  DFFQXL \E3_data_10b_out_reg[7] (.CK (rc_gclk_448), .D
       (E3_temp_4b[1]), .Q (en_out3[7]));
  DFFQXL \E3_data_10b_out_reg[8] (.CK (rc_gclk_448), .D
       (E3_temp_4b[2]), .Q (en_out3[8]));
  DFFQXL \E3_data_10b_out_reg[9] (.CK (rc_gclk_448), .D
       (E3_temp_4b[3]), .Q (en_out3[9]));
  DFFQXL \E3_temp_4b_reg[0] (.CK (rc_gclk_451), .D (n_209), .Q
       (E3_temp_4b[0]));
  DFFQXL \E3_temp_4b_reg[1] (.CK (rc_gclk_451), .D (n_217), .Q
       (E3_temp_4b[1]));
  DFFQXL \E3_temp_4b_reg[2] (.CK (rc_gclk_451), .D (n_188), .Q
       (E3_temp_4b[2]));
  DFFQXL \E3_temp_4b_reg[3] (.CK (rc_gclk_451), .D (n_146), .Q
       (E3_temp_4b[3]));
  DFFQXL \E3_temp_6b_reg[0] (.CK (rc_gclk_451), .D (n_268), .Q
       (E3_temp_6b[0]));
  DFFQXL \E3_temp_6b_reg[1] (.CK (rc_gclk_451), .D (n_240), .Q
       (E3_temp_6b[1]));
  DFFQXL \E3_temp_6b_reg[2] (.CK (rc_gclk_451), .D (n_252), .Q
       (E3_temp_6b[2]));
  DFFQXL \E3_temp_6b_reg[3] (.CK (rc_gclk_451), .D (n_271), .Q
       (E3_temp_6b[3]));
  DFFQXL \E3_temp_6b_reg[4] (.CK (rc_gclk_451), .D (n_263), .Q
       (E3_temp_6b[4]));
  DFFQXL \E3_temp_6b_reg[5] (.CK (rc_gclk_451), .D (n_275), .Q
       (E3_temp_6b[5]));
  DFFQXL \E4_data_10b_out_reg[0] (.CK (rc_gclk_448), .D
       (E4_temp_6b[0]), .Q (en_out4[0]));
  DFFQXL \E4_data_10b_out_reg[1] (.CK (rc_gclk_448), .D
       (E4_temp_6b[1]), .Q (en_out4[1]));
  DFFQXL \E4_data_10b_out_reg[2] (.CK (rc_gclk_448), .D
       (E4_temp_6b[2]), .Q (en_out4[2]));
  DFFQXL \E4_data_10b_out_reg[3] (.CK (rc_gclk_448), .D
       (E4_temp_6b[3]), .Q (en_out4[3]));
  DFFQXL \E4_data_10b_out_reg[4] (.CK (rc_gclk_448), .D
       (E4_temp_6b[4]), .Q (en_out4[4]));
  DFFQXL \E4_data_10b_out_reg[5] (.CK (rc_gclk_448), .D
       (E4_temp_6b[5]), .Q (en_out4[5]));
  DFFQXL \E4_data_10b_out_reg[6] (.CK (rc_gclk_448), .D
       (E4_temp_4b[0]), .Q (en_out4[6]));
  DFFQXL \E4_data_10b_out_reg[7] (.CK (rc_gclk_448), .D
       (E4_temp_4b[1]), .Q (en_out4[7]));
  DFFQXL \E4_data_10b_out_reg[8] (.CK (rc_gclk_448), .D
       (E4_temp_4b[2]), .Q (en_out4[8]));
  DFFQXL \E4_data_10b_out_reg[9] (.CK (rc_gclk_448), .D
       (E4_temp_4b[3]), .Q (en_out4[9]));
  DFFQXL \E4_temp_4b_reg[0] (.CK (rc_gclk_451), .D (n_210), .Q
       (E4_temp_4b[0]));
  DFFQXL \E4_temp_4b_reg[1] (.CK (rc_gclk_451), .D (n_214), .Q
       (E4_temp_4b[1]));
  DFFQXL \E4_temp_4b_reg[2] (.CK (rc_gclk_451), .D (n_178), .Q
       (E4_temp_4b[2]));
  DFFQXL \E4_temp_4b_reg[3] (.CK (rc_gclk_451), .D (n_147), .Q
       (E4_temp_4b[3]));
  DFFQXL \E4_temp_6b_reg[0] (.CK (rc_gclk_451), .D (n_267), .Q
       (E4_temp_6b[0]));
  DFFQXL \E4_temp_6b_reg[1] (.CK (rc_gclk_451), .D (n_238), .Q
       (E4_temp_6b[1]));
  DFFQXL \E4_temp_6b_reg[2] (.CK (rc_gclk_451), .D (n_250), .Q
       (E4_temp_6b[2]));
  DFFQXL \E4_temp_6b_reg[3] (.CK (rc_gclk_451), .D (n_273), .Q
       (E4_temp_6b[3]));
  DFFQXL \E4_temp_6b_reg[4] (.CK (rc_gclk_451), .D (n_259), .Q
       (E4_temp_6b[4]));
  DFFQXL \E4_temp_6b_reg[5] (.CK (rc_gclk_451), .D (n_278), .Q
       (E4_temp_6b[5]));
  DFFQXL P1S01_ser_out_reg(.CK (rc_gclk_703), .D (P1S01_shift_reg[0]),
       .Q (ser_out));
  DFFQXL \P1S01_shift_reg_reg[0] (.CK (clk), .D (n_350), .Q
       (P1S01_shift_reg[0]));
  DFFQXL \P1S01_shift_reg_reg[1] (.CK (clk), .D (n_342), .Q
       (P1S01_shift_reg[1]));
  DFFQXL \P1S01_shift_reg_reg[2] (.CK (clk), .D (n_334), .Q
       (P1S01_shift_reg[2]));
  DFFQXL \P1S01_shift_reg_reg[3] (.CK (clk), .D (n_326), .Q
       (P1S01_shift_reg[3]));
  DFFQXL \P1S01_shift_reg_reg[4] (.CK (clk), .D (n_318), .Q
       (P1S01_shift_reg[4]));
  DFFQXL \P1S01_shift_reg_reg[5] (.CK (clk), .D (n_310), .Q
       (P1S01_shift_reg[5]));
  DFFQXL \P1S01_shift_reg_reg[6] (.CK (clk), .D (n_301), .Q
       (P1S01_shift_reg[6]));
  DFFQXL \P1S01_shift_reg_reg[7] (.CK (clk), .D (n_294), .Q
       (P1S01_shift_reg[7]));
  DFFQXL \P1S01_shift_reg_reg[8] (.CK (clk), .D (n_286), .Q
       (P1S01_shift_reg[8]));
  DFFQXL \P1S01_shift_reg_reg[9] (.CK (clk), .D (n_249), .Q
       (P1S01_shift_reg[9]));
  DFFQXL P1S02_ser_out_reg(.CK (rc_gclk_703), .D (P1S02_shift_reg[0]),
       .Q (ser_out2));
  DFFQXL \P1S02_shift_reg_reg[0] (.CK (clk), .D (n_349), .Q
       (P1S02_shift_reg[0]));
  DFFQXL \P1S02_shift_reg_reg[1] (.CK (clk), .D (n_341), .Q
       (P1S02_shift_reg[1]));
  DFFQXL \P1S02_shift_reg_reg[2] (.CK (clk), .D (n_333), .Q
       (P1S02_shift_reg[2]));
  DFFQXL \P1S02_shift_reg_reg[3] (.CK (clk), .D (n_325), .Q
       (P1S02_shift_reg[3]));
  DFFQXL \P1S02_shift_reg_reg[4] (.CK (clk), .D (n_317), .Q
       (P1S02_shift_reg[4]));
  DFFQXL \P1S02_shift_reg_reg[5] (.CK (clk), .D (n_309), .Q
       (P1S02_shift_reg[5]));
  DFFQXL \P1S02_shift_reg_reg[6] (.CK (clk), .D (n_300), .Q
       (P1S02_shift_reg[6]));
  DFFQXL \P1S02_shift_reg_reg[7] (.CK (clk), .D (n_293), .Q
       (P1S02_shift_reg[7]));
  DFFQXL \P1S02_shift_reg_reg[8] (.CK (clk), .D (n_285), .Q
       (P1S02_shift_reg[8]));
  DFFQXL \P1S02_shift_reg_reg[9] (.CK (clk), .D (n_248), .Q
       (P1S02_shift_reg[9]));
  DFFQXL P1S03_ser_out_reg(.CK (rc_gclk_703), .D (P1S03_shift_reg[0]),
       .Q (ser_out3));
  DFFQXL \P1S03_shift_reg_reg[0] (.CK (clk), .D (n_348), .Q
       (P1S03_shift_reg[0]));
  DFFQXL \P1S03_shift_reg_reg[1] (.CK (clk), .D (n_340), .Q
       (P1S03_shift_reg[1]));
  DFFQXL \P1S03_shift_reg_reg[2] (.CK (clk), .D (n_332), .Q
       (P1S03_shift_reg[2]));
  DFFQXL \P1S03_shift_reg_reg[3] (.CK (clk), .D (n_324), .Q
       (P1S03_shift_reg[3]));
  DFFQXL \P1S03_shift_reg_reg[4] (.CK (clk), .D (n_316), .Q
       (P1S03_shift_reg[4]));
  DFFQXL \P1S03_shift_reg_reg[5] (.CK (clk), .D (n_308), .Q
       (P1S03_shift_reg[5]));
  DFFQXL \P1S03_shift_reg_reg[6] (.CK (clk), .D (n_302), .Q
       (P1S03_shift_reg[6]));
  DFFQXL \P1S03_shift_reg_reg[7] (.CK (clk), .D (n_292), .Q
       (P1S03_shift_reg[7]));
  DFFQXL \P1S03_shift_reg_reg[8] (.CK (clk), .D (n_284), .Q
       (P1S03_shift_reg[8]));
  DFFQXL \P1S03_shift_reg_reg[9] (.CK (clk), .D (n_247), .Q
       (P1S03_shift_reg[9]));
  DFFQXL P1S04_ser_out_reg(.CK (rc_gclk_703), .D (P1S04_shift_reg[0]),
       .Q (ser_out4));
  DFFQXL \P1S04_shift_reg_reg[0] (.CK (clk), .D (n_347), .Q
       (P1S04_shift_reg[0]));
  DFFQXL \P1S04_shift_reg_reg[1] (.CK (clk), .D (n_339), .Q
       (P1S04_shift_reg[1]));
  DFFQXL \P1S04_shift_reg_reg[2] (.CK (clk), .D (n_331), .Q
       (P1S04_shift_reg[2]));
  DFFQXL \P1S04_shift_reg_reg[3] (.CK (clk), .D (n_323), .Q
       (P1S04_shift_reg[3]));
  DFFQXL \P1S04_shift_reg_reg[4] (.CK (clk), .D (n_315), .Q
       (P1S04_shift_reg[4]));
  DFFQXL \P1S04_shift_reg_reg[5] (.CK (clk), .D (n_307), .Q
       (P1S04_shift_reg[5]));
  DFFQXL \P1S04_shift_reg_reg[6] (.CK (clk), .D (n_299), .Q
       (P1S04_shift_reg[6]));
  DFFQXL \P1S04_shift_reg_reg[7] (.CK (clk), .D (n_291), .Q
       (P1S04_shift_reg[7]));
  DFFQXL \P1S04_shift_reg_reg[8] (.CK (clk), .D (n_283), .Q
       (P1S04_shift_reg[8]));
  DFFQXL \P1S04_shift_reg_reg[9] (.CK (clk), .D (n_246), .Q
       (P1S04_shift_reg[9]));
  DFFHQX1 \S1P01_par_out_reg[0] (.CK (rc_gclk), .D (n_358), .Q
       (si_out[0]));
  DFFHQX1 \S1P01_par_out_reg[1] (.CK (rc_gclk), .D (n_71), .Q
       (si_out[1]));
  DFFHQX1 \S1P01_par_out_reg[2] (.CK (rc_gclk), .D (n_70), .Q
       (si_out[2]));
  DFFHQX1 \S1P01_par_out_reg[3] (.CK (rc_gclk), .D (n_69), .Q
       (si_out[3]));
  DFFHQX1 \S1P01_par_out_reg[4] (.CK (rc_gclk), .D (n_68), .Q
       (si_out[4]));
  DFFHQX1 \S1P01_par_out_reg[5] (.CK (rc_gclk), .D (n_67), .Q
       (si_out[5]));
  DFFHQX1 \S1P01_par_out_reg[6] (.CK (rc_gclk), .D (n_66), .Q
       (si_out[6]));
  DFFQXL \S1P01_par_out_reg[7] (.CK (rc_gclk), .D (n_65), .Q
       (si_out[7]));
  DFFQXL \S1P01_par_out_reg[8] (.CK (rc_gclk), .D (n_64), .Q
       (si_out[8]));
  DFFQXL \S1P01_par_out_reg[9] (.CK (rc_gclk), .D (n_63), .Q
       (si_out[9]));
  DFFQXL \S1P01_shift_reg_reg[0] (.CK (rc_gclk_695), .D (n_71), .Q
       (S1P01_shift_reg[0]));
  DFFQXL \S1P01_shift_reg_reg[1] (.CK (rc_gclk_695), .D (n_70), .Q
       (S1P01_shift_reg[1]));
  DFFQXL \S1P01_shift_reg_reg[2] (.CK (rc_gclk_695), .D (n_69), .Q
       (S1P01_shift_reg[2]));
  DFFQXL \S1P01_shift_reg_reg[3] (.CK (rc_gclk_695), .D (n_68), .Q
       (S1P01_shift_reg[3]));
  DFFQXL \S1P01_shift_reg_reg[4] (.CK (rc_gclk_695), .D (n_67), .Q
       (S1P01_shift_reg[4]));
  DFFQXL \S1P01_shift_reg_reg[5] (.CK (rc_gclk_695), .D (n_66), .Q
       (S1P01_shift_reg[5]));
  DFFQXL \S1P01_shift_reg_reg[6] (.CK (rc_gclk_695), .D (n_65), .Q
       (S1P01_shift_reg[6]));
  DFFQXL \S1P01_shift_reg_reg[7] (.CK (rc_gclk_695), .D (n_64), .Q
       (S1P01_shift_reg[7]));
  DFFQXL \S1P01_shift_reg_reg[8] (.CK (rc_gclk_695), .D (n_63), .Q
       (S1P01_shift_reg[8]));
  DFFQXL \S1P01_shift_reg_reg[9] (.CK (rc_gclk_695), .D (n_354), .Q
       (S1P01_shift_reg[9]));
  DFFHQX1 \S1P02_par_out_reg[0] (.CK (rc_gclk), .D (n_357), .Q
       (si_out2[0]));
  DFFHQX1 \S1P02_par_out_reg[1] (.CK (rc_gclk), .D (n_62), .Q
       (si_out2[1]));
  DFFHQX1 \S1P02_par_out_reg[2] (.CK (rc_gclk), .D (n_61), .Q
       (si_out2[2]));
  DFFHQX1 \S1P02_par_out_reg[3] (.CK (rc_gclk), .D (n_60), .Q
       (si_out2[3]));
  DFFHQX1 \S1P02_par_out_reg[4] (.CK (rc_gclk), .D (n_59), .Q
       (si_out2[4]));
  DFFHQX1 \S1P02_par_out_reg[5] (.CK (rc_gclk), .D (n_58), .Q
       (si_out2[5]));
  DFFHQX1 \S1P02_par_out_reg[6] (.CK (rc_gclk), .D (n_57), .Q
       (si_out2[6]));
  DFFQXL \S1P02_par_out_reg[7] (.CK (rc_gclk), .D (n_56), .Q
       (si_out2[7]));
  DFFQXL \S1P02_par_out_reg[8] (.CK (rc_gclk), .D (n_55), .Q
       (si_out2[8]));
  DFFQXL \S1P02_par_out_reg[9] (.CK (rc_gclk), .D (n_54), .Q
       (si_out2[9]));
  DFFQXL \S1P02_shift_reg_reg[0] (.CK (rc_gclk_695), .D (n_62), .Q
       (S1P02_shift_reg[0]));
  DFFQXL \S1P02_shift_reg_reg[1] (.CK (rc_gclk_695), .D (n_61), .Q
       (S1P02_shift_reg[1]));
  DFFQXL \S1P02_shift_reg_reg[2] (.CK (rc_gclk_695), .D (n_60), .Q
       (S1P02_shift_reg[2]));
  DFFQXL \S1P02_shift_reg_reg[3] (.CK (rc_gclk_695), .D (n_59), .Q
       (S1P02_shift_reg[3]));
  DFFQXL \S1P02_shift_reg_reg[4] (.CK (rc_gclk_695), .D (n_58), .Q
       (S1P02_shift_reg[4]));
  DFFQXL \S1P02_shift_reg_reg[5] (.CK (rc_gclk_695), .D (n_57), .Q
       (S1P02_shift_reg[5]));
  DFFQXL \S1P02_shift_reg_reg[6] (.CK (rc_gclk_695), .D (n_56), .Q
       (S1P02_shift_reg[6]));
  DFFQXL \S1P02_shift_reg_reg[7] (.CK (rc_gclk_695), .D (n_55), .Q
       (S1P02_shift_reg[7]));
  DFFQXL \S1P02_shift_reg_reg[8] (.CK (rc_gclk_695), .D (n_54), .Q
       (S1P02_shift_reg[8]));
  DFFQXL \S1P02_shift_reg_reg[9] (.CK (rc_gclk_695), .D (n_353), .Q
       (S1P02_shift_reg[9]));
  DFFHQX1 \S1P03_par_out_reg[0] (.CK (rc_gclk), .D (n_356), .Q
       (si_out3[0]));
  DFFHQX1 \S1P03_par_out_reg[1] (.CK (rc_gclk), .D (n_53), .Q
       (si_out3[1]));
  DFFHQX1 \S1P03_par_out_reg[2] (.CK (rc_gclk), .D (n_52), .Q
       (si_out3[2]));
  DFFHQX1 \S1P03_par_out_reg[3] (.CK (rc_gclk), .D (n_51), .Q
       (si_out3[3]));
  DFFHQX1 \S1P03_par_out_reg[4] (.CK (rc_gclk), .D (n_50), .Q
       (si_out3[4]));
  DFFHQX1 \S1P03_par_out_reg[5] (.CK (rc_gclk), .D (n_49), .Q
       (si_out3[5]));
  DFFHQX1 \S1P03_par_out_reg[6] (.CK (rc_gclk), .D (n_48), .Q
       (si_out3[6]));
  DFFQXL \S1P03_par_out_reg[7] (.CK (rc_gclk), .D (n_47), .Q
       (si_out3[7]));
  DFFQXL \S1P03_par_out_reg[8] (.CK (rc_gclk), .D (n_46), .Q
       (si_out3[8]));
  DFFQXL \S1P03_par_out_reg[9] (.CK (rc_gclk), .D (n_45), .Q
       (si_out3[9]));
  DFFQXL \S1P03_shift_reg_reg[0] (.CK (rc_gclk_695), .D (n_53), .Q
       (S1P03_shift_reg[0]));
  DFFQXL \S1P03_shift_reg_reg[1] (.CK (rc_gclk_695), .D (n_52), .Q
       (S1P03_shift_reg[1]));
  DFFQXL \S1P03_shift_reg_reg[2] (.CK (rc_gclk_695), .D (n_51), .Q
       (S1P03_shift_reg[2]));
  DFFQXL \S1P03_shift_reg_reg[3] (.CK (rc_gclk_695), .D (n_50), .Q
       (S1P03_shift_reg[3]));
  DFFQXL \S1P03_shift_reg_reg[4] (.CK (rc_gclk_695), .D (n_49), .Q
       (S1P03_shift_reg[4]));
  DFFQXL \S1P03_shift_reg_reg[5] (.CK (rc_gclk_695), .D (n_48), .Q
       (S1P03_shift_reg[5]));
  DFFQXL \S1P03_shift_reg_reg[6] (.CK (rc_gclk_695), .D (n_47), .Q
       (S1P03_shift_reg[6]));
  DFFQXL \S1P03_shift_reg_reg[7] (.CK (rc_gclk_695), .D (n_46), .Q
       (S1P03_shift_reg[7]));
  DFFQXL \S1P03_shift_reg_reg[8] (.CK (rc_gclk_695), .D (n_45), .Q
       (S1P03_shift_reg[8]));
  DFFQXL \S1P03_shift_reg_reg[9] (.CK (rc_gclk_695), .D (n_352), .Q
       (S1P03_shift_reg[9]));
  DFFHQX1 \S1P04_par_out_reg[0] (.CK (rc_gclk), .D (n_355), .Q
       (si_out4[0]));
  DFFHQX1 \S1P04_par_out_reg[1] (.CK (rc_gclk), .D (n_44), .Q
       (si_out4[1]));
  DFFHQX1 \S1P04_par_out_reg[2] (.CK (rc_gclk), .D (n_43), .Q
       (si_out4[2]));
  DFFHQX1 \S1P04_par_out_reg[3] (.CK (rc_gclk), .D (n_42), .Q
       (si_out4[3]));
  DFFHQX1 \S1P04_par_out_reg[4] (.CK (rc_gclk), .D (n_41), .Q
       (si_out4[4]));
  DFFHQX1 \S1P04_par_out_reg[5] (.CK (rc_gclk), .D (n_40), .Q
       (si_out4[5]));
  DFFHQX1 \S1P04_par_out_reg[6] (.CK (rc_gclk), .D (n_39), .Q
       (si_out4[6]));
  DFFQXL \S1P04_par_out_reg[7] (.CK (rc_gclk), .D (n_38), .Q
       (si_out4[7]));
  DFFQXL \S1P04_par_out_reg[8] (.CK (rc_gclk), .D (n_37), .Q
       (si_out4[8]));
  DFFQXL \S1P04_par_out_reg[9] (.CK (rc_gclk), .D (n_36), .Q
       (si_out4[9]));
  DFFQXL \S1P04_shift_reg_reg[0] (.CK (rc_gclk_695), .D (n_44), .Q
       (S1P04_shift_reg[0]));
  DFFQXL \S1P04_shift_reg_reg[1] (.CK (rc_gclk_695), .D (n_43), .Q
       (S1P04_shift_reg[1]));
  DFFQXL \S1P04_shift_reg_reg[2] (.CK (rc_gclk_695), .D (n_42), .Q
       (S1P04_shift_reg[2]));
  DFFQXL \S1P04_shift_reg_reg[3] (.CK (rc_gclk_695), .D (n_41), .Q
       (S1P04_shift_reg[3]));
  DFFQXL \S1P04_shift_reg_reg[4] (.CK (rc_gclk_695), .D (n_40), .Q
       (S1P04_shift_reg[4]));
  DFFQXL \S1P04_shift_reg_reg[5] (.CK (rc_gclk_695), .D (n_39), .Q
       (S1P04_shift_reg[5]));
  DFFQXL \S1P04_shift_reg_reg[6] (.CK (rc_gclk_695), .D (n_38), .Q
       (S1P04_shift_reg[6]));
  DFFQXL \S1P04_shift_reg_reg[7] (.CK (rc_gclk_695), .D (n_37), .Q
       (S1P04_shift_reg[7]));
  DFFQXL \S1P04_shift_reg_reg[8] (.CK (rc_gclk_695), .D (n_36), .Q
       (S1P04_shift_reg[8]));
  DFFQXL \S1P04_shift_reg_reg[9] (.CK (rc_gclk_695), .D (n_351), .Q
       (S1P04_shift_reg[9]));
  DFFQXL \d_next_reg[0] (.CK (rc_gclk_701), .D (n_266), .Q (d_next[0]));
  DFFQXL \d_next_reg[1] (.CK (rc_gclk_701), .D (n_370), .Q (d_next[1]));
  DFFQXL \d_next_reg[2] (.CK (rc_gclk_701), .D (n_374), .Q (d_next[2]));
  DFFQXL \s_next_reg[0] (.CK (rc_gclk_705), .D (n_212), .Q (s_next[0]));
  DFFQXL \s_next_reg[1] (.CK (rc_gclk_705), .D (n_192), .Q (s_next[1]));
  DFFQXL \s_next_reg[2] (.CK (rc_gclk_705), .D (n_211), .Q (s_next[2]));
  NOR2BX1 g3837__8428(.AN (S1P01_shift_reg[0]), .B (rst), .Y (n_358));
  NOR2BX1 g3838__5526(.AN (S1P02_shift_reg[0]), .B (rst), .Y (n_357));
  NOR2BX1 g3839__6783(.AN (S1P03_shift_reg[0]), .B (rst), .Y (n_356));
  NOR2BX1 g3840__3680(.AN (S1P04_shift_reg[0]), .B (rst), .Y (n_355));
  NOR2BX1 g3989__1617(.AN (ser_out), .B (rst), .Y (n_354));
  NOR2BX1 g3990__2802(.AN (ser_out2), .B (rst), .Y (n_353));
  NOR2BX1 g3991__1705(.AN (ser_out3), .B (rst), .Y (n_352));
  NOR2BX1 g3992__5122(.AN (ser_out4), .B (rst), .Y (n_351));
  NOR2XL g4001__8246(.A (rst), .B (n_346), .Y (n_350));
  NOR2XL g4002__7098(.A (rst), .B (n_345), .Y (n_349));
  NOR2XL g4003__6131(.A (rst), .B (n_344), .Y (n_348));
  NOR2XL g4004__1881(.A (rst), .B (n_343), .Y (n_347));
  AOI22XL g4005__5115(.A0 (P1S01_shift_reg[1]), .A1 (n_72), .B0
       (en_out[0]), .B1 (p_en), .Y (n_346));
  AOI22XL g4006__7482(.A0 (P1S02_shift_reg[1]), .A1 (n_72), .B0
       (en_out2[0]), .B1 (p_en), .Y (n_345));
  AOI22XL g4007__4733(.A0 (P1S03_shift_reg[1]), .A1 (n_72), .B0
       (en_out3[0]), .B1 (p_en), .Y (n_344));
  AOI22XL g4008__6161(.A0 (P1S04_shift_reg[1]), .A1 (n_72), .B0
       (en_out4[0]), .B1 (p_en), .Y (n_343));
  NOR2XL g4013__9315(.A (rst), .B (n_338), .Y (n_342));
  NOR2XL g4014__9945(.A (rst), .B (n_337), .Y (n_341));
  NOR2XL g4015__2883(.A (rst), .B (n_336), .Y (n_340));
  NOR2XL g4016__2346(.A (rst), .B (n_335), .Y (n_339));
  AOI22XL g4017__1666(.A0 (P1S01_shift_reg[2]), .A1 (n_72), .B0
       (en_out[1]), .B1 (p_en), .Y (n_338));
  AOI22XL g4018__7410(.A0 (P1S02_shift_reg[2]), .A1 (n_72), .B0
       (en_out2[1]), .B1 (p_en), .Y (n_337));
  AOI22XL g4019__6417(.A0 (P1S03_shift_reg[2]), .A1 (n_72), .B0
       (en_out3[1]), .B1 (p_en), .Y (n_336));
  AOI22XL g4020__5477(.A0 (P1S04_shift_reg[2]), .A1 (n_72), .B0
       (en_out4[1]), .B1 (p_en), .Y (n_335));
  NOR2XL g4025__2398(.A (rst), .B (n_330), .Y (n_334));
  NOR2XL g4026__5107(.A (rst), .B (n_329), .Y (n_333));
  NOR2XL g4027__6260(.A (rst), .B (n_328), .Y (n_332));
  NOR2XL g4028__4319(.A (rst), .B (n_327), .Y (n_331));
  AOI22XL g4029__8428(.A0 (P1S01_shift_reg[3]), .A1 (n_72), .B0
       (en_out[2]), .B1 (p_en), .Y (n_330));
  AOI22XL g4030__5526(.A0 (P1S02_shift_reg[3]), .A1 (n_72), .B0
       (en_out2[2]), .B1 (p_en), .Y (n_329));
  AOI22XL g4031__6783(.A0 (P1S03_shift_reg[3]), .A1 (n_72), .B0
       (en_out3[2]), .B1 (p_en), .Y (n_328));
  AOI22XL g4032__3680(.A0 (P1S04_shift_reg[3]), .A1 (n_72), .B0
       (en_out4[2]), .B1 (p_en), .Y (n_327));
  NOR2XL g4037__1617(.A (rst), .B (n_322), .Y (n_326));
  NOR2XL g4038__2802(.A (rst), .B (n_321), .Y (n_325));
  NOR2XL g4039__1705(.A (rst), .B (n_320), .Y (n_324));
  NOR2XL g4040__5122(.A (rst), .B (n_319), .Y (n_323));
  AOI22XL g4041__8246(.A0 (P1S01_shift_reg[4]), .A1 (n_72), .B0
       (en_out[3]), .B1 (p_en), .Y (n_322));
  AOI22XL g4042__7098(.A0 (P1S02_shift_reg[4]), .A1 (n_72), .B0
       (en_out2[3]), .B1 (p_en), .Y (n_321));
  AOI22XL g4043__6131(.A0 (P1S03_shift_reg[4]), .A1 (n_72), .B0
       (en_out3[3]), .B1 (p_en), .Y (n_320));
  AOI22XL g4044__1881(.A0 (P1S04_shift_reg[4]), .A1 (n_72), .B0
       (en_out4[3]), .B1 (p_en), .Y (n_319));
  NOR2XL g4049__5115(.A (rst), .B (n_314), .Y (n_318));
  NOR2XL g4050__7482(.A (rst), .B (n_313), .Y (n_317));
  NOR2XL g4051__4733(.A (rst), .B (n_312), .Y (n_316));
  NOR2XL g4052__6161(.A (rst), .B (n_311), .Y (n_315));
  AOI22XL g4053__9315(.A0 (P1S01_shift_reg[5]), .A1 (n_72), .B0
       (en_out[4]), .B1 (p_en), .Y (n_314));
  AOI22XL g4054__9945(.A0 (P1S02_shift_reg[5]), .A1 (n_72), .B0
       (en_out2[4]), .B1 (p_en), .Y (n_313));
  AOI22XL g4055__2883(.A0 (P1S03_shift_reg[5]), .A1 (n_72), .B0
       (en_out3[4]), .B1 (p_en), .Y (n_312));
  AOI22XL g4056__2346(.A0 (P1S04_shift_reg[5]), .A1 (n_72), .B0
       (en_out4[4]), .B1 (p_en), .Y (n_311));
  NOR2XL g4061__1666(.A (rst), .B (n_305), .Y (n_310));
  NOR2XL g4062__7410(.A (rst), .B (n_304), .Y (n_309));
  NOR2XL g4063__6417(.A (rst), .B (n_306), .Y (n_308));
  NOR2XL g4064__5477(.A (rst), .B (n_303), .Y (n_307));
  AOI22XL g4065__2398(.A0 (P1S03_shift_reg[6]), .A1 (n_72), .B0
       (en_out3[5]), .B1 (p_en), .Y (n_306));
  AOI22XL g4066__5107(.A0 (P1S01_shift_reg[6]), .A1 (n_72), .B0
       (en_out[5]), .B1 (p_en), .Y (n_305));
  AOI22XL g4067__6260(.A0 (P1S02_shift_reg[6]), .A1 (n_72), .B0
       (en_out2[5]), .B1 (p_en), .Y (n_304));
  AOI22XL g4068__4319(.A0 (P1S04_shift_reg[6]), .A1 (n_72), .B0
       (en_out4[5]), .B1 (p_en), .Y (n_303));
  NOR2XL g4073__8428(.A (rst), .B (n_296), .Y (n_302));
  NOR2XL g4074__5526(.A (rst), .B (n_297), .Y (n_301));
  NOR2XL g4075__6783(.A (rst), .B (n_298), .Y (n_300));
  NOR2XL g4076__3680(.A (rst), .B (n_295), .Y (n_299));
  AOI22XL g4077__1617(.A0 (P1S02_shift_reg[7]), .A1 (n_72), .B0
       (en_out2[6]), .B1 (p_en), .Y (n_298));
  AOI22XL g4078__2802(.A0 (P1S01_shift_reg[7]), .A1 (n_72), .B0
       (en_out[6]), .B1 (p_en), .Y (n_297));
  AOI22XL g4079__1705(.A0 (P1S03_shift_reg[7]), .A1 (n_72), .B0
       (en_out3[6]), .B1 (p_en), .Y (n_296));
  AOI22XL g4080__5122(.A0 (P1S04_shift_reg[7]), .A1 (n_72), .B0
       (en_out4[6]), .B1 (p_en), .Y (n_295));
  NOR2XL g4085__8246(.A (rst), .B (n_290), .Y (n_294));
  NOR2XL g4086__7098(.A (rst), .B (n_289), .Y (n_293));
  NOR2XL g4087__6131(.A (rst), .B (n_288), .Y (n_292));
  NOR2XL g4088__1881(.A (rst), .B (n_287), .Y (n_291));
  AOI22XL g4089__5115(.A0 (P1S01_shift_reg[8]), .A1 (n_72), .B0
       (en_out[7]), .B1 (p_en), .Y (n_290));
  AOI22XL g4090__7482(.A0 (P1S02_shift_reg[8]), .A1 (n_72), .B0
       (en_out2[7]), .B1 (p_en), .Y (n_289));
  AOI22XL g4091__4733(.A0 (P1S03_shift_reg[8]), .A1 (n_72), .B0
       (en_out3[7]), .B1 (p_en), .Y (n_288));
  AOI22XL g4092__6161(.A0 (P1S04_shift_reg[8]), .A1 (n_72), .B0
       (en_out4[7]), .B1 (p_en), .Y (n_287));
  NOR2XL g4105__9315(.A (rst), .B (n_282), .Y (n_286));
  NOR2XL g4110__9945(.A (rst), .B (n_281), .Y (n_285));
  NOR2XL g4111__2883(.A (rst), .B (n_280), .Y (n_284));
  NOR2XL g4112__2346(.A (rst), .B (n_279), .Y (n_283));
  AOI22XL g4131__1666(.A0 (P1S01_shift_reg[9]), .A1 (n_72), .B0
       (en_out[8]), .B1 (p_en), .Y (n_282));
  AOI22XL g4132__7410(.A0 (P1S02_shift_reg[9]), .A1 (n_72), .B0
       (en_out2[8]), .B1 (p_en), .Y (n_281));
  AOI22XL g4133__6417(.A0 (P1S03_shift_reg[9]), .A1 (n_72), .B0
       (en_out3[8]), .B1 (p_en), .Y (n_280));
  AOI22XL g4134__5477(.A0 (P1S04_shift_reg[9]), .A1 (n_72), .B0
       (en_out4[8]), .B1 (p_en), .Y (n_279));
  NOR2XL g4143__2398(.A (rst), .B (n_257), .Y (n_278));
  NOR2XL g4144__5107(.A (rst), .B (n_256), .Y (n_277));
  NAND2XL g4145__6260(.A (n_372), .B (n_361), .Y (n_370));
  NOR2XL g4146__4319(.A (rst), .B (n_258), .Y (n_276));
  NOR2XL g4147__8428(.A (rst), .B (n_255), .Y (n_275));
  NOR2XL g4148__5526(.A (rst), .B (n_254), .Y (n_274));
  NOR2XL g4149__6783(.A (rst), .B (n_261), .Y (n_273));
  NOR2XL g4150__3680(.A (rst), .B (n_260), .Y (n_272));
  NOR2XL g4151__1617(.A (rst), .B (n_265), .Y (n_271));
  NAND2BXL g4152__2802(.AN (n_364), .B (s_state[1]), .Y (n_367));
  AOI21X1 g4153__1705(.A0 (n_229), .A1 (n_244), .B0 (rst), .Y (n_270));
  AOI21X1 g4154__5122(.A0 (n_227), .A1 (n_242), .B0 (rst), .Y (n_269));
  AOI21X1 g4155__8246(.A0 (n_228), .A1 (n_243), .B0 (rst), .Y (n_268));
  AOI21X1 g4156__7098(.A0 (n_226), .A1 (n_245), .B0 (rst), .Y (n_267));
  NAND3BXL g4157__6131(.AN (n_150), .B (n_363), .C (n_364), .Y (n_266));
  NAND2BXL g4170__1881(.AN (n_373), .B (n_366), .Y (n_361));
  AOI221X1 g4171__5115(.A0 (data_in[18]), .A1 (n_198), .B0 (n_33), .B1
       (n_221), .C0 (n_223), .Y (n_265));
  AOI21X1 g4172__7482(.A0 (n_236), .A1 (n_175), .B0 (rst), .Y (n_264));
  AOI21X1 g4173__4733(.A0 (n_235), .A1 (n_174), .B0 (rst), .Y (n_263));
  AOI21X1 g4174__6161(.A0 (n_234), .A1 (n_171), .B0 (rst), .Y (n_262));
  AOI221X1 g4175__9315(.A0 (data_in[26]), .A1 (n_197), .B0 (n_31), .B1
       (n_216), .C0 (n_225), .Y (n_261));
  AOI221X1 g4176__9945(.A0 (data_in[10]), .A1 (n_195), .B0 (n_32), .B1
       (n_219), .C0 (n_224), .Y (n_260));
  AOI21X1 g4177__2883(.A0 (n_237), .A1 (n_177), .B0 (rst), .Y (n_259));
  AOI221X1 g4178__2346(.A0 (data_in[2]), .A1 (n_193), .B0 (n_34), .B1
       (n_220), .C0 (n_222), .Y (n_258));
  AOI222X1 g4179__1666(.A0 (data_in[26]), .A1 (n_216), .B0 (n_106), .B1
       (n_31), .C0 (data_in[24]), .C1 (n_190), .Y (n_257));
  AOI222X1 g4180__7410(.A0 (data_in[10]), .A1 (n_219), .B0 (n_101), .B1
       (n_32), .C0 (data_in[8]), .C1 (n_189), .Y (n_256));
  AOI222X1 g4181__6417(.A0 (data_in[18]), .A1 (n_221), .B0 (n_103), .B1
       (n_33), .C0 (data_in[16]), .C1 (n_191), .Y (n_255));
  AOI222X1 g4182__5477(.A0 (data_in[2]), .A1 (n_220), .B0 (n_102), .B1
       (n_34), .C0 (data_in[0]), .C1 (n_194), .Y (n_254));
  OR2XL g4183__2398(.A (n_373), .B (n_366), .Y (n_364));
  NOR2XL g4196__5107(.A (rst), .B (n_233), .Y (n_253));
  NOR2XL g4197__6260(.A (rst), .B (n_232), .Y (n_252));
  NOR2XL g4198__4319(.A (rst), .B (n_231), .Y (n_251));
  NOR2XL g4199__8428(.A (rst), .B (n_230), .Y (n_250));
  NOR3BXL g4200__5526(.AN (en_out[9]), .B (rst), .C (n_72), .Y (n_249));
  NOR3BXL g4201__6783(.AN (en_out2[9]), .B (rst), .C (n_72), .Y
       (n_248));
  NOR3BXL g4202__3680(.AN (en_out3[9]), .B (rst), .C (n_72), .Y
       (n_247));
  NOR3BXL g4203__1617(.AN (en_out4[9]), .B (rst), .C (n_72), .Y
       (n_246));
  AOI22X1 g4204__2802(.A0 (n_186), .A1 (n_152), .B0 (data_in[24]), .B1
       (n_216), .Y (n_245));
  AOI22X1 g4205__1705(.A0 (n_179), .A1 (n_168), .B0 (data_in[8]), .B1
       (n_219), .Y (n_244));
  AOI22X1 g4206__5122(.A0 (n_196), .A1 (n_160), .B0 (data_in[16]), .B1
       (n_221), .Y (n_243));
  AOI22X1 g4207__8246(.A0 (n_187), .A1 (n_155), .B0 (data_in[0]), .B1
       (n_220), .Y (n_242));
  OAI21XL g4208__7098(.A0 (n_95), .A1 (n_410), .B0 (n_35), .Y (n_366));
  NOR2XL g4223__6131(.A (rst), .B (n_205), .Y (n_241));
  NOR2XL g4224__1881(.A (rst), .B (n_206), .Y (n_240));
  NOR2XL g4225__5115(.A (rst), .B (n_204), .Y (n_239));
  NOR2XL g4226__7482(.A (rst), .B (n_213), .Y (n_238));
  OAI21X1 g4227__4733(.A0 (data_in[25]), .A1 (n_129), .B0 (n_130), .Y
       (n_237));
  OAI21X1 g4228__6161(.A0 (data_in[9]), .A1 (n_107), .B0 (n_104), .Y
       (n_236));
  OAI21X1 g4229__9315(.A0 (data_in[17]), .A1 (n_128), .B0 (n_131), .Y
       (n_235));
  OAI21X1 g4230__9945(.A0 (data_in[1]), .A1 (n_100), .B0 (n_105), .Y
       (n_234));
  AOI221X1 g4231__2883(.A0 (n_122), .A1 (n_101), .B0 (n_96), .B1
       (n_153), .C0 (n_184), .Y (n_233));
  AOI221X1 g4232__2346(.A0 (n_124), .A1 (n_103), .B0 (n_118), .B1
       (n_149), .C0 (n_183), .Y (n_232));
  AOI221X1 g4233__1666(.A0 (n_126), .A1 (n_102), .B0 (n_119), .B1
       (n_151), .C0 (n_182), .Y (n_231));
  AOI221X1 g4234__7410(.A0 (n_98), .A1 (n_106), .B0 (n_97), .B1
       (n_154), .C0 (n_185), .Y (n_230));
  AOI221X1 g4235__6417(.A0 (n_123), .A1 (n_101), .B0 (n_107), .B1
       (n_153), .C0 (n_169), .Y (n_229));
  AOI221X1 g4236__5477(.A0 (n_125), .A1 (n_103), .B0 (n_128), .B1
       (n_149), .C0 (n_166), .Y (n_228));
  AOI221X1 g4237__2398(.A0 (n_127), .A1 (n_102), .B0 (n_100), .B1
       (n_151), .C0 (n_167), .Y (n_227));
  AOI221X1 g4238__5107(.A0 (n_99), .A1 (n_106), .B0 (n_129), .B1
       (n_154), .C0 (n_165), .Y (n_226));
  OAI32X1 g4239__6260(.A0 (data_in[24]), .A1 (data_in[25]), .A2
       (n_202), .B0 (n_76), .B1 (n_31), .Y (n_225));
  OAI32X1 g4240__4319(.A0 (data_in[8]), .A1 (data_in[9]), .A2 (n_200),
       .B0 (n_86), .B1 (n_32), .Y (n_224));
  OAI32X1 g4241__8428(.A0 (data_in[16]), .A1 (data_in[17]), .A2
       (n_201), .B0 (n_93), .B1 (n_33), .Y (n_223));
  OAI32X1 g4242__5526(.A0 (data_in[0]), .A1 (data_in[1]), .A2 (n_203),
       .B0 (n_90), .B1 (n_34), .Y (n_222));
  NOR2XL g4252__6783(.A (rst), .B (n_176), .Y (n_218));
  NOR2XL g4253__3680(.A (rst), .B (n_170), .Y (n_217));
  NAND2XL g4254__1617(.A (n_411), .B (n_199), .Y (n_408));
  NOR2BX1 g4255__2802(.AN (n_128), .B (data_in[17]), .Y (n_221));
  NOR2BX1 g4256__1705(.AN (n_100), .B (data_in[1]), .Y (n_220));
  NOR2BX1 g4257__5122(.AN (n_107), .B (data_in[9]), .Y (n_219));
  AOI21X1 g4258__8246(.A0 (n_115), .A1 (n_158), .B0 (rst), .Y (n_215));
  NOR2XL g4259__7098(.A (rst), .B (n_172), .Y (n_214));
  AOI211XL g4260__6131(.A0 (n_99), .A1 (n_109), .B0 (data_in[28]), .C0
       (n_165), .Y (n_213));
  AOI21XL g4261__1881(.A0 (s_state[2]), .A1 (n_148), .B0 (s_state[0]),
       .Y (n_212));
  NAND2XL g4262__5115(.A (n_35), .B (n_199), .Y (n_211));
  AOI21X1 g4263__7482(.A0 (n_142), .A1 (n_156), .B0 (rst), .Y (n_210));
  AOI21X1 g4264__4733(.A0 (n_117), .A1 (n_159), .B0 (rst), .Y (n_209));
  NOR2XL g4265__6161(.A (rst), .B (n_173), .Y (n_208));
  AOI21X1 g4266__9315(.A0 (n_140), .A1 (n_157), .B0 (rst), .Y (n_207));
  NAND3BXL g4267__9945(.AN (n_362), .B (n_373), .C (n_372), .Y (n_371));
  AOI211XL g4268__2883(.A0 (n_125), .A1 (n_111), .B0 (data_in[20]), .C0
       (n_166), .Y (n_206));
  AOI211XL g4269__2346(.A0 (n_123), .A1 (n_108), .B0 (data_in[12]), .C0
       (n_169), .Y (n_205));
  AOI211XL g4270__1666(.A0 (n_127), .A1 (n_110), .B0 (data_in[4]), .C0
       (n_167), .Y (n_204));
  OAI22X1 g4271__7410(.A0 (n_148), .A1 (n_365), .B0 (s_state[2]), .B1
       (s_state[1]), .Y (n_410));
  NOR2BX1 g4272__6417(.AN (n_129), .B (data_in[25]), .Y (n_216));
  INVXL g4273(.A (n_155), .Y (n_203));
  INVXL g4274(.A (n_152), .Y (n_202));
  INVXL g4275(.A (n_160), .Y (n_201));
  INVXL g4276(.A (n_168), .Y (n_200));
  NAND2BXL g4277__5477(.AN (n_103), .B (n_164), .Y (n_198));
  NAND2BXL g4282__2398(.AN (n_106), .B (n_162), .Y (n_197));
  OAI2BB1X1 g4283__5107(.A0N (n_84), .A1N (n_131), .B0 (n_124), .Y
       (n_196));
  NAND2BXL g4284__6260(.AN (n_101), .B (n_163), .Y (n_195));
  OAI21XL g4285__4319(.A0 (data_in[2]), .A1 (n_90), .B0 (n_161), .Y
       (n_194));
  NAND2BXL g4287__8428(.AN (n_102), .B (n_161), .Y (n_193));
  NAND2XL g4288__5526(.A (n_445), .B (n_411), .Y (n_192));
  NAND2XL g4289__6783(.A (s_state[2]), .B (n_365), .Y (n_409));
  OAI21XL g4290__3680(.A0 (data_in[18]), .A1 (n_93), .B0 (n_164), .Y
       (n_191));
  OAI21XL g4291__1617(.A0 (data_in[26]), .A1 (n_76), .B0 (n_162), .Y
       (n_190));
  OAI21XL g4292__2802(.A0 (data_in[10]), .A1 (n_86), .B0 (n_163), .Y
       (n_189));
  NAND2BXL g4293__1705(.AN (n_365), .B (n_148), .Y (n_199));
  OR2XL g4294__5122(.A (n_375), .B (n_372), .Y (n_363));
  NAND2BXL g4295__8246(.AN (n_150), .B (n_374), .Y (n_362));
  NOR3X1 g4296__7098(.A (data_in[21]), .B (rst), .C (n_136), .Y
       (n_188));
  OAI2BB1X1 g4297__6131(.A0N (n_73), .A1N (n_105), .B0 (n_126), .Y
       (n_187));
  OAI2BB1X1 g4298__1881(.A0N (n_74), .A1N (n_130), .B0 (n_98), .Y
       (n_186));
  AOI2BB1XL g4299__5115(.A0N (n_77), .A1N (n_130), .B0 (n_143), .Y
       (n_185));
  AOI2BB1XL g4300__7482(.A0N (n_87), .A1N (n_104), .B0 (n_137), .Y
       (n_184));
  AOI2BB1XL g4301__4733(.A0N (n_75), .A1N (n_131), .B0 (n_113), .Y
       (n_183));
  AOI2BB1XL g4302__6161(.A0N (n_78), .A1N (n_105), .B0 (n_112), .Y
       (n_182));
  NOR3X1 g4303__9315(.A (data_in[13]), .B (rst), .C (n_133), .Y
       (n_181));
  NOR3X1 g4304__9945(.A (data_in[5]), .B (rst), .C (n_132), .Y (n_180));
  OAI2BB1X1 g4305__2883(.A0N (n_85), .A1N (n_104), .B0 (n_122), .Y
       (n_179));
  NOR3X1 g4306__2346(.A (data_in[29]), .B (rst), .C (n_134), .Y
       (n_178));
  AOI211XL g4307__1666(.A0 (data_in[25]), .A1 (n_77), .B0 (n_99), .C0
       (n_109), .Y (n_177));
  AOI221X1 g4308__7410(.A0 (data_in[15]), .A1 (n_94), .B0
       (data_in[13]), .B1 (n_139), .C0 (n_133), .Y (n_176));
  AOI211XL g4309__6417(.A0 (data_in[9]), .A1 (n_87), .B0 (n_123), .C0
       (n_108), .Y (n_175));
  AOI211XL g4310__5477(.A0 (data_in[17]), .A1 (n_75), .B0 (n_125), .C0
       (n_111), .Y (n_174));
  AOI221X1 g4311__2398(.A0 (data_in[7]), .A1 (n_82), .B0 (data_in[5]),
       .B1 (n_114), .C0 (n_132), .Y (n_173));
  AOI221X1 g4312__5107(.A0 (data_in[31]), .A1 (n_81), .B0
       (data_in[29]), .B1 (n_141), .C0 (n_134), .Y (n_172));
  AOI211XL g4313__6260(.A0 (data_in[1]), .A1 (n_78), .B0 (n_127), .C0
       (n_110), .Y (n_171));
  AOI221X1 g4314__4319(.A0 (data_in[23]), .A1 (n_83), .B0
       (data_in[21]), .B1 (n_116), .C0 (n_136), .Y (n_170));
  OR2XL g4315__8428(.A (n_83), .B (n_136), .Y (n_159));
  OR2XL g4316__5526(.A (n_82), .B (n_132), .Y (n_158));
  OR2XL g4317__6783(.A (n_94), .B (n_133), .Y (n_157));
  OR2XL g4318__3680(.A (n_81), .B (n_134), .Y (n_156));
  NOR2X1 g4319__1617(.A (n_104), .B (n_137), .Y (n_169));
  AOI21X1 g4320__2802(.A0 (data_in[11]), .A1 (data_in[12]), .B0
       (n_107), .Y (n_168));
  NOR2X1 g4321__1705(.A (n_105), .B (n_112), .Y (n_167));
  NOR2X1 g4322__5122(.A (n_131), .B (n_113), .Y (n_166));
  NOR2X1 g4323__8246(.A (n_130), .B (n_143), .Y (n_165));
  NOR2X1 g4324__7098(.A (data_in[20]), .B (n_111), .Y (n_164));
  NOR2X1 g4325__6131(.A (data_in[12]), .B (n_108), .Y (n_163));
  NOR2X1 g4326__1881(.A (data_in[28]), .B (n_109), .Y (n_162));
  NOR2X1 g4327__5115(.A (data_in[4]), .B (n_110), .Y (n_161));
  AOI21X1 g4329__7482(.A0 (data_in[19]), .A1 (data_in[20]), .B0
       (n_128), .Y (n_160));
  NAND3X1 g4330__4733(.A (d_state[0]), .B (d_state[1]), .C (n_135), .Y
       (n_374));
  OR2XL g4331__6161(.A (s_state[1]), .B (n_138), .Y (n_411));
  NOR3X1 g4332__9315(.A (data_in[30]), .B (rst), .C (n_81), .Y (n_147));
  NOR3X1 g4333__9945(.A (data_in[22]), .B (rst), .C (n_83), .Y (n_146));
  NOR3X1 g4334__2883(.A (data_in[14]), .B (rst), .C (n_94), .Y (n_145));
  NOR3X1 g4335__2346(.A (data_in[6]), .B (rst), .C (n_82), .Y (n_144));
  AOI21X1 g4336__1666(.A0 (data_in[3]), .A1 (data_in[4]), .B0 (n_100),
       .Y (n_155));
  OAI2BB1X1 g4337__7410(.A0N (data_in[24]), .A1N (n_91), .B0 (n_31), .Y
       (n_154));
  OAI2BB1X1 g4338__6417(.A0N (data_in[8]), .A1N (n_89), .B0 (n_32), .Y
       (n_153));
  NAND3X1 g4339__5477(.A (count_2[1]), .B (count_2[3]), .C (n_120), .Y
       (n_375));
  AOI21X1 g4340__2398(.A0 (data_in[27]), .A1 (data_in[28]), .B0
       (n_129), .Y (n_152));
  OAI2BB1X1 g4341__5107(.A0N (data_in[0]), .A1N (n_88), .B0 (n_34), .Y
       (n_151));
  NAND3BXL g4342__6260(.AN (s_state[0]), .B (s_state[1]), .C (n_79), .Y
       (n_445));
  NOR4BX1 g4343__4319(.AN (d_state[3]), .B (d_state[2]), .C
       (d_state[0]), .D (d_state[1]), .Y (n_150));
  OAI2BB1X1 g4344__8428(.A0N (data_in[16]), .A1N (n_92), .B0 (n_33), .Y
       (n_149));
  NAND3X1 g4345__5526(.A (count[1]), .B (count[3]), .C (n_121), .Y
       (n_148));
  NAND3BXL g4346__6783(.AN (d_state[0]), .B (d_state[1]), .C (n_135),
       .Y (n_372));
  NAND3BXL g4347__3680(.AN (d_state[1]), .B (d_state[0]), .C (n_135),
       .Y (n_373));
  NAND3BXL g4348__1617(.AN (s_state[0]), .B (s_state[2]), .C (n_80), .Y
       (n_365));
  INVXL g4349(.A (n_141), .Y (n_142));
  INVXL g4350(.A (n_139), .Y (n_140));
  INVX1 g4352(.A (n_127), .Y (n_126));
  INVX1 g4353(.A (n_125), .Y (n_124));
  INVX1 g4354(.A (n_123), .Y (n_122));
  NOR2X1 g4355__2802(.A (count[0]), .B (count[2]), .Y (n_121));
  OR2XL g4356__1705(.A (rst), .B (s_en), .Y (n_369));
  NOR2X1 g4357__5122(.A (count_2[0]), .B (count_2[2]), .Y (n_120));
  NOR2X1 g4358__8246(.A (rst), .B (en_en), .Y (E1_n_298));
  NOR2X1 g4359__7098(.A (data_in[1]), .B (data_in[4]), .Y (n_119));
  NOR2X1 g4361__6131(.A (data_in[17]), .B (data_in[20]), .Y (n_118));
  NAND2X1 g4362__1881(.A (data_in[25]), .B (data_in[27]), .Y (n_143));
  NOR2BX1 g4363__5115(.AN (data_in[30]), .B (data_in[31]), .Y (n_141));
  NOR2BX1 g4364__7482(.AN (data_in[14]), .B (data_in[15]), .Y (n_139));
  NAND2XL g4365__4733(.A (s_state[0]), .B (n_79), .Y (n_138));
  NAND2X1 g4366__6161(.A (data_in[9]), .B (data_in[11]), .Y (n_137));
  NOR2BX1 g4367__9315(.AN (data_in[23]), .B (data_in[22]), .Y (n_136));
  NOR2BX1 g4368__9945(.AN (d_state[2]), .B (d_state[3]), .Y (n_135));
  NOR2BX1 g4369__2883(.AN (data_in[31]), .B (data_in[30]), .Y (n_134));
  NOR2BX1 g4370__2346(.AN (data_in[15]), .B (data_in[14]), .Y (n_133));
  NOR2BX1 g4371__1666(.AN (data_in[7]), .B (data_in[6]), .Y (n_132));
  NAND2X1 g4372__7410(.A (data_in[16]), .B (data_in[18]), .Y (n_131));
  NAND2X1 g4373__6417(.A (data_in[24]), .B (data_in[26]), .Y (n_130));
  NOR2X1 g4374__5477(.A (data_in[27]), .B (data_in[28]), .Y (n_129));
  NOR2X1 g4375__2398(.A (data_in[19]), .B (data_in[20]), .Y (n_128));
  NOR2X1 g4376__5107(.A (data_in[0]), .B (data_in[2]), .Y (n_127));
  NOR2X1 g4377__6260(.A (data_in[16]), .B (data_in[18]), .Y (n_125));
  NOR2X1 g4378__4319(.A (data_in[8]), .B (data_in[10]), .Y (n_123));
  INVXL g4379(.A (n_116), .Y (n_117));
  INVXL g4380(.A (n_114), .Y (n_115));
  INVX1 g4381(.A (n_99), .Y (n_98));
  NOR2XL g4382__8428(.A (rst), .B (p_en), .Y (P1S01_n_37));
  NOR2X1 g4383__5526(.A (data_in[25]), .B (data_in[28]), .Y (n_97));
  NOR2X1 g4384__6783(.A (data_in[9]), .B (data_in[12]), .Y (n_96));
  NOR2BX1 g4385__3680(.AN (data_in[22]), .B (data_in[23]), .Y (n_116));
  NOR2BX1 g4386__1617(.AN (data_in[6]), .B (data_in[7]), .Y (n_114));
  NAND2X1 g4387__2802(.A (data_in[17]), .B (data_in[19]), .Y (n_113));
  NAND2X1 g4388__1705(.A (data_in[1]), .B (data_in[3]), .Y (n_112));
  NOR2X1 g4389__5122(.A (data_in[19]), .B (n_84), .Y (n_111));
  NOR2X1 g4390__8246(.A (data_in[3]), .B (n_73), .Y (n_110));
  NOR2X1 g4391__7098(.A (data_in[27]), .B (n_74), .Y (n_109));
  NOR2X1 g4392__6131(.A (data_in[11]), .B (n_85), .Y (n_108));
  NOR2X1 g4394__1881(.A (data_in[11]), .B (data_in[12]), .Y (n_107));
  NOR2X1 g4396__5115(.A (data_in[25]), .B (n_76), .Y (n_106));
  NAND2X1 g4397__7482(.A (data_in[0]), .B (data_in[2]), .Y (n_105));
  NAND2X1 g4398__4733(.A (data_in[8]), .B (data_in[10]), .Y (n_104));
  NOR2X1 g4400__6161(.A (data_in[17]), .B (n_93), .Y (n_103));
  NOR2X1 g4401__9315(.A (data_in[1]), .B (n_90), .Y (n_102));
  NOR2X1 g4403__9945(.A (data_in[9]), .B (n_86), .Y (n_101));
  NOR2X1 g4404__2883(.A (data_in[3]), .B (data_in[4]), .Y (n_100));
  NOR2X1 g4405__2346(.A (data_in[24]), .B (data_in[26]), .Y (n_99));
  INVXL g4406(.A (start), .Y (n_95));
  INVX1 g4407(.A (data_in[13]), .Y (n_94));
  INVX1 g4408(.A (data_in[19]), .Y (n_93));
  INVXL g4409(.A (data_in[18]), .Y (n_92));
  INVXL g4411(.A (data_in[26]), .Y (n_91));
  INVX1 g4412(.A (data_in[3]), .Y (n_90));
  INVXL g4413(.A (data_in[10]), .Y (n_89));
  INVXL g4414(.A (data_in[2]), .Y (n_88));
  INVXL g4416(.A (data_in[12]), .Y (n_87));
  INVX1 g4417(.A (data_in[11]), .Y (n_86));
  INVX1 g4418(.A (data_in[9]), .Y (n_85));
  INVX1 g4419(.A (data_in[17]), .Y (n_84));
  INVX1 g4421(.A (data_in[21]), .Y (n_83));
  INVX1 g4422(.A (data_in[5]), .Y (n_82));
  INVX1 g4423(.A (data_in[29]), .Y (n_81));
  INVXL g4424(.A (s_state[1]), .Y (n_80));
  INVXL g4425(.A (s_state[2]), .Y (n_79));
  INVXL g4427(.A (data_in[4]), .Y (n_78));
  INVXL g4428(.A (data_in[28]), .Y (n_77));
  INVX1 g4430(.A (data_in[27]), .Y (n_76));
  INVXL g4431(.A (data_in[20]), .Y (n_75));
  INVX1 g4432(.A (data_in[25]), .Y (n_74));
  INVX1 g4433(.A (data_in[1]), .Y (n_73));
  INVX2 g4434(.A (p_en), .Y (n_72));
  NOR2BX1 g4435__1666(.AN (S1P01_shift_reg[1]), .B (rst), .Y (n_71));
  NOR2BX1 g4436__7410(.AN (S1P01_shift_reg[2]), .B (rst), .Y (n_70));
  NOR2BX1 g4437__6417(.AN (S1P01_shift_reg[3]), .B (rst), .Y (n_69));
  NOR2BX1 g4438__5477(.AN (S1P01_shift_reg[4]), .B (rst), .Y (n_68));
  NOR2BX1 g4439__2398(.AN (S1P01_shift_reg[5]), .B (rst), .Y (n_67));
  NOR2BX1 g4440__5107(.AN (S1P01_shift_reg[6]), .B (rst), .Y (n_66));
  NOR2BX1 g4441__6260(.AN (S1P01_shift_reg[7]), .B (rst), .Y (n_65));
  NOR2BX1 g4442__4319(.AN (S1P01_shift_reg[8]), .B (rst), .Y (n_64));
  NOR2BX1 g4443__8428(.AN (S1P01_shift_reg[9]), .B (rst), .Y (n_63));
  NOR2BX1 g4444__5526(.AN (S1P02_shift_reg[1]), .B (rst), .Y (n_62));
  NOR2BX1 g4445__6783(.AN (S1P02_shift_reg[2]), .B (rst), .Y (n_61));
  NOR2BX1 g4446__3680(.AN (S1P02_shift_reg[3]), .B (rst), .Y (n_60));
  NOR2BX1 g4447__1617(.AN (S1P02_shift_reg[4]), .B (rst), .Y (n_59));
  NOR2BX1 g4448__2802(.AN (S1P02_shift_reg[5]), .B (rst), .Y (n_58));
  NOR2BX1 g4449__1705(.AN (S1P02_shift_reg[6]), .B (rst), .Y (n_57));
  NOR2BX1 g4450__5122(.AN (S1P02_shift_reg[7]), .B (rst), .Y (n_56));
  NOR2BX1 g4451__8246(.AN (S1P02_shift_reg[8]), .B (rst), .Y (n_55));
  NOR2BX1 g4452__7098(.AN (S1P02_shift_reg[9]), .B (rst), .Y (n_54));
  NOR2BX1 g4453__6131(.AN (S1P03_shift_reg[1]), .B (rst), .Y (n_53));
  NOR2BX1 g4454__1881(.AN (S1P03_shift_reg[2]), .B (rst), .Y (n_52));
  NOR2BX1 g4455__5115(.AN (S1P03_shift_reg[3]), .B (rst), .Y (n_51));
  NOR2BX1 g4456__7482(.AN (S1P03_shift_reg[4]), .B (rst), .Y (n_50));
  NOR2BX1 g4457__4733(.AN (S1P03_shift_reg[5]), .B (rst), .Y (n_49));
  NOR2BX1 g4458__6161(.AN (S1P03_shift_reg[6]), .B (rst), .Y (n_48));
  NOR2BX1 g4459__9315(.AN (S1P03_shift_reg[7]), .B (rst), .Y (n_47));
  NOR2BX1 g4460__9945(.AN (S1P03_shift_reg[8]), .B (rst), .Y (n_46));
  NOR2BX1 g4461__2883(.AN (S1P03_shift_reg[9]), .B (rst), .Y (n_45));
  NOR2BX1 g4462__2346(.AN (S1P04_shift_reg[1]), .B (rst), .Y (n_44));
  NOR2BX1 g4463__1666(.AN (S1P04_shift_reg[2]), .B (rst), .Y (n_43));
  NOR2BX1 g4464__7410(.AN (S1P04_shift_reg[3]), .B (rst), .Y (n_42));
  NOR2BX1 g4465__6417(.AN (S1P04_shift_reg[4]), .B (rst), .Y (n_41));
  NOR2BX1 g4466__5477(.AN (S1P04_shift_reg[5]), .B (rst), .Y (n_40));
  NOR2BX1 g4467__2398(.AN (S1P04_shift_reg[6]), .B (rst), .Y (n_39));
  NOR2BX1 g4468__5107(.AN (S1P04_shift_reg[7]), .B (rst), .Y (n_38));
  NOR2BX1 g4469__6260(.AN (S1P04_shift_reg[8]), .B (rst), .Y (n_37));
  NOR2BX1 g4470__4319(.AN (S1P04_shift_reg[9]), .B (rst), .Y (n_36));
  NAND2BX1 g2__8428(.AN (n_138), .B (s_state[1]), .Y (n_35));
  NAND2BX1 g4471__5526(.AN (data_in[0]), .B (data_in[2]), .Y (n_34));
  NAND2BX1 g4472__6783(.AN (data_in[16]), .B (data_in[18]), .Y (n_33));
  NAND2BXL g4473__3680(.AN (rst), .B (s_en), .Y (n_368));
  NAND2BX1 g4474__1617(.AN (data_in[8]), .B (data_in[10]), .Y (n_32));
  NAND2BX1 g4475__2802(.AN (data_in[24]), .B (data_in[26]), .Y (n_31));
  DFFHQX1 \count_2_reg[3] (.CK (rc_gclk_697), .D (n_29), .Q
       (count_2[3]));
  DFFHQX1 \count_reg[3] (.CK (rc_gclk_699), .D (n_30), .Q (count[3]));
  NOR2XL g1567__1705(.A (n_28), .B (n_365), .Y (n_30));
  NOR2XL g1568__5122(.A (n_27), .B (n_14), .Y (n_29));
  DFFHQX1 \count_reg[2] (.CK (rc_gclk_699), .D (n_26), .Q (count[2]));
  DFFHQX1 \count_2_reg[2] (.CK (rc_gclk_697), .D (n_25), .Q
       (count_2[2]));
  XNOR2X1 g1571__8246(.A (count[3]), .B (n_20), .Y (n_28));
  XNOR2X1 g1572__7098(.A (count_2[3]), .B (n_19), .Y (n_27));
  NOR2XL g1573__6131(.A (n_24), .B (n_365), .Y (n_26));
  NOR2XL g1574__1881(.A (n_23), .B (n_372), .Y (n_25));
  DFFHQX1 \count_2_reg[1] (.CK (rc_gclk_697), .D (n_21), .Q
       (count_2[1]));
  DFFHQX1 \count_reg[1] (.CK (rc_gclk_699), .D (n_22), .Q (count[1]));
  XNOR2X1 g1577__5115(.A (count[2]), .B (n_8), .Y (n_24));
  XNOR2X1 g1578__7482(.A (count_2[2]), .B (n_9), .Y (n_23));
  SDFFQX1 s_en_reg(.CK (clk), .D (s_en), .SI (n_11), .SE (n_15), .Q
       (s_en));
  NOR2XL g1580__4733(.A (n_16), .B (n_365), .Y (n_22));
  SDFFQX1 de_en_reg(.CK (rc_gclk_708), .D (de_en), .SI (n_0), .SE
       (n_2), .Q (de_en));
  NOR2XL g1582__6161(.A (n_17), .B (n_14), .Y (n_21));
  AND2XL g1583__9315(.A (count[2]), .B (n_8), .Y (n_20));
  AND2XL g1584__9945(.A (count_2[2]), .B (n_9), .Y (n_19));
  DFFHQX1 \count_2_reg[0] (.CK (rc_gclk_697), .D (n_18), .Q
       (count_2[0]));
  MDFFHQX4 p_en_reg(.CK (clk), .D0 (n_1), .D1 (p_en), .S0 (s_state[2]),
       .Q (p_en));
  SDFFQX1 en_en_reg(.CK (rc_gclk_708), .D (en_en), .SI (n_411), .SE
       (n_410), .Q (en_en));
  DFFHQX1 \d_state_reg[0] (.CK (clk), .D (n_6), .Q (d_state[0]));
  DFFQXL \d_state_reg[2] (.CK (clk), .D (n_4), .Q (d_state[2]));
  DFFHQX1 \d_state_reg[1] (.CK (clk), .D (n_5), .Q (d_state[1]));
  DFFQXL \d_state_reg[3] (.CK (clk), .D (n_7), .Q (d_state[3]));
  DFFHQX1 \s_state_reg[0] (.CK (clk), .D (n_10), .Q (s_state[0]));
  DFFHQX1 \s_state_reg[1] (.CK (clk), .D (n_3), .Q (s_state[1]));
  NOR2XL g1594__2883(.A (count_2[0]), .B (n_14), .Y (n_18));
  XNOR2X1 g1595__2346(.A (count_2[0]), .B (count_2[1]), .Y (n_17));
  XNOR2X1 g1596__1666(.A (count[0]), .B (count[1]), .Y (n_16));
  NAND3XL g1597__7410(.A (n_373), .B (n_374), .C (n_363), .Y (n_15));
  DFFHQX1 \s_state_reg[2] (.CK (clk), .D (n_13), .Q (s_state[2]));
  DFFHQX1 \count_reg[0] (.CK (rc_gclk_699), .D (n_12), .Q (count[0]));
  NOR2BX1 g1600__6417(.AN (s_next[2]), .B (rst), .Y (n_13));
  DFFQXL start_reg(.CK (rc_gclk_708), .D (n_366), .Q (start));
  DFFQXL \d_next_reg[3] (.CK (rc_gclk_701), .D (n_0), .Q (d_next[3]));
  NOR2XL g1603__5477(.A (count[0]), .B (n_365), .Y (n_12));
  NAND2XL g1604__2398(.A (n_372), .B (n_364), .Y (n_11));
  NOR2BX1 g1605__5107(.AN (s_next[0]), .B (rst), .Y (n_10));
  NAND2BX1 g1606__6260(.AN (n_372), .B (n_375), .Y (n_14));
  NOR2BX1 g1607__4319(.AN (d_next[3]), .B (rst), .Y (n_7));
  OR2XL g1608__8428(.A (d_next[0]), .B (rst), .Y (n_6));
  NOR2BX1 g1609__5526(.AN (d_next[1]), .B (rst), .Y (n_5));
  OR2XL g1610__6783(.A (d_next[2]), .B (rst), .Y (n_4));
  NOR2BX1 g1611__3680(.AN (s_next[1]), .B (rst), .Y (n_3));
  NAND2BXL g1612__1617(.AN (n_362), .B (n_361), .Y (n_2));
  AND2XL g1613__2802(.A (count_2[1]), .B (count_2[0]), .Y (n_9));
  AND2XL g1614__1705(.A (count[1]), .B (count[0]), .Y (n_8));
  INVXL g1615(.A (n_445), .Y (n_1));
  INVXL g1616(.A (n_374), .Y (n_0));
  INVXL RC_CG_INVERTER(.A (E1_n_298), .Y (n_449));
endmodule

